function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
}

/** Convierte notas de release (HTML de GitHub) a texto legible. */
export function plainTextReleaseNotes(raw?: string | null): string {
  if (!raw?.trim()) return ''

  const withBreaks = raw
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>\s*<p[^>]*>/gi, '\n\n')
    .replace(/<\/p>/gi, '\n')
    .replace(/<\/li>\s*/gi, '\n')
    .replace(/<li[^>]*>/gi, '• ')
    .replace(/<h[1-6][^>]*>/gi, '\n')
    .replace(/<\/h[1-6]>/gi, '\n')

  const withLinks = withBreaks.replace(
    /<a [^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi,
    (_, url: string, label: string) => {
      const text = decodeHtmlEntities(label.replace(/<[^>]+>/g, '').trim())
      if (!text || text === url) return url
      return `${text}: ${url}`
    }
  )

  const stripped = decodeHtmlEntities(withLinks.replace(/<[^>]+>/g, ''))

  return stripped
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join('\n')
    .trim()
}

/** GitHub auto-genera solo un enlace "Full Changelog" sin contenido útil. */
export function isAutoGeneratedChangelogOnly(notes: string): boolean {
  if (!notes.trim()) return true
  const lines = notes.split('\n').filter(Boolean)
  if (lines.length === 0) return true
  return lines.every(
    (line) =>
      /^Full Changelog\s*:/i.test(line) ||
      /^v[\d.]+(\.{3}|…)[\d.]+$/i.test(line) ||
      /^https?:\/\/github\.com\//i.test(line)
  )
}
