import { app, BrowserWindow, ipcMain } from 'electron'
import { spawn } from 'child_process'
import { existsSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { autoUpdater, type UpdateDownloadedEvent } from 'electron-updater'
import { isAutoGeneratedChangelogOnly, plainTextReleaseNotes } from './releaseNotes'

const GITHUB_OWNER = 'JRNCarrizo'
const GITHUB_REPO = 'bodegaStock'
const GITHUB_RELEASES_URL = `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases`
/** URL estable al latest.yml (sin api.github.com). */
const GENERIC_UPDATE_URL = `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest/download`

/** Evita doble clic seguido. */
const CHECK_DEBOUNCE_MS = 45 * 1000
/** Tras un 429 real en api.github.com (solo fallback). */
const RATE_LIMIT_COOLDOWN_MS = 30 * 60 * 1000

export type UpdateStatusPayload =
  | { type: 'checking' }
  | { type: 'available'; version: string; releaseNotes?: string }
  | { type: 'not-available'; version: string }
  | { type: 'download-progress'; percent: number; transferred: number; total: number }
  | { type: 'downloaded'; version: string }
  | { type: 'installing'; version?: string }
  | {
      type: 'error'
      message: string
      rateLimited?: boolean
      retryAfterMs?: number
    }

type CooldownState = {
  lastCheckAt: number
  blockedUntil: number
}

function cooldownFilePath(): string {
  return join(app.getPath('userData'), 'update-github-cooldown.json')
}

function readCooldownState(): CooldownState {
  try {
    const raw = readFileSync(cooldownFilePath(), 'utf8')
    const parsed = JSON.parse(raw) as Partial<CooldownState>
    return {
      lastCheckAt: typeof parsed.lastCheckAt === 'number' ? parsed.lastCheckAt : 0,
      blockedUntil: typeof parsed.blockedUntil === 'number' ? parsed.blockedUntil : 0
    }
  } catch {
    return { lastCheckAt: 0, blockedUntil: 0 }
  }
}

function writeCooldownState(state: CooldownState): void {
  try {
    writeFileSync(cooldownFilePath(), JSON.stringify(state), 'utf8')
  } catch {
    /* ignore disk errors */
  }
}

function minutesLeft(ms: number): number {
  return Math.max(1, Math.ceil(ms / 60_000))
}

function getCooldownRemainingMs(now = Date.now(), opts?: { force?: boolean }): number {
  if (opts?.force) return 0
  const state = readCooldownState()
  const untilBlocked = state.blockedUntil
  const untilDebounce = state.lastCheckAt + CHECK_DEBOUNCE_MS
  const until = Math.max(untilDebounce, untilBlocked)
  return Math.max(0, until - now)
}

function markCheckAttempt(now = Date.now()): void {
  const state = readCooldownState()
  writeCooldownState({ ...state, lastCheckAt: now })
}

function markRateLimited(now = Date.now()): void {
  writeCooldownState({
    lastCheckAt: now,
    blockedUntil: now + RATE_LIMIT_COOLDOWN_MS
  })
}

function isRateLimitError(err: unknown): boolean {
  const message = err instanceof Error ? err.message : String(err)
  const status =
    err && typeof err === 'object' && 'statusCode' in err
      ? Number((err as { statusCode?: number }).statusCode)
      : NaN
  if (status === 429 || status === 403) return true
  if (/429|Too Many Requests|rate limit exceeded|secondary rate limit/i.test(message)) return true
  return false
}

function cooldownMessage(retryAfterMs: number, rateLimited: boolean): string {
  if (rateLimited) {
    const mins = minutesLeft(retryAfterMs)
    return `GitHub limitó las consultas. Esperá ~${mins} min y volvé a buscar, o instalá el Setup a mano desde Releases.`
  }
  const secs = Math.max(1, Math.ceil(retryAfterMs / 1000))
  return `Esperá ~${secs} s antes de volver a buscar (evitá consultas repetidas).`
}

function sendStatus(win: BrowserWindow | null, status: UpdateStatusPayload) {
  if (win && !win.isDestroyed()) {
    win.webContents.send('update-status', status)
  }
}

function broadcastStatus(status: UpdateStatusPayload) {
  for (const win of BrowserWindow.getAllWindows()) {
    sendStatus(win, status)
  }
}

let handlersRegistered = false
/** true mientras se lanza el NSIS: no cortar el proceso con app.exit */
let installingUpdate = false
/** Ruta del Setup descargado (para abrirlo con UI visible). */
let downloadedInstallerPath: string | null = null
/** Evita checks concurrentes a GitHub. */
let checkInFlight = false

export function isInstallingUpdate(): boolean {
  return installingUpdate
}

function configureAutoUpdaterFeed(): boolean {
  if (!app.isPackaged) return false

  const updateYml = join(process.resourcesPath, 'app-update.yml')
  if (existsSync(updateYml)) return true

  autoUpdater.setFeedURL({
    provider: 'generic',
    url: GENERIC_UPDATE_URL
  })
  return true
}

function clearRateLimitBlock(): void {
  const state = readCooldownState()
  writeCooldownState({ ...state, blockedUntil: 0 })
}

function friendlyUpdateError(err: unknown): string {
  const message = err instanceof Error ? err.message : String(err)

  if (message.includes('app-update.yml')) {
    return 'Esta versión no incluye actualizaciones automáticas. Descargá la última versión desde GitHub Releases e instalá manualmente.'
  }

  if (isRateLimitError(err)) {
    const retryAfterMs = getCooldownRemainingMs() || RATE_LIMIT_COOLDOWN_MS
    return cooldownMessage(retryAfterMs, true)
  }

  if (message.includes('404') || message.includes('Not Found')) {
    return 'No se encontró un release compatible en GitHub. Descargá el instalador manualmente desde Releases.'
  }

  if (/ERR_HTTP2|HTTP2_PROTOCOL|net::ERR_/i.test(message)) {
    return 'Falló la descarga automática (red/GitHub). Probá de nuevo o instalá manualmente el Setup desde GitHub Releases.'
  }

  // Evitar pegar HTML completo de GitHub en la UI.
  if (message.includes('<!DOCTYPE html>') || message.length > 280) {
    return 'No se pudo consultar actualizaciones en GitHub. Probá más tarde o instalá el Setup desde Releases.'
  }

  return message
}

function resolveInstallerPath(info?: UpdateDownloadedEvent): string | null {
  if (info?.downloadedFile && existsSync(info.downloadedFile)) {
    return info.downloadedFile
  }
  if (downloadedInstallerPath && existsSync(downloadedInstallerPath)) {
    return downloadedInstallerPath
  }
  const helper = (autoUpdater as unknown as { downloadedUpdateHelper?: { file?: string | null } })
    .downloadedUpdateHelper
  if (helper?.file && existsSync(helper.file)) return helper.file
  return null
}

/**
 * Abre el Setup cuando este proceso ya terminó (evita el cartel "programa en uso").
 */
function launchInstallerAfterAppExit(installerPath: string): void {
  const escaped = installerPath.replace(/"/g, '""')
  const comspec = process.env.ComSpec ?? 'cmd.exe'
  const script = `timeout /t 2 /nobreak >nul & start "" "${escaped}"`
  spawn(comspec, ['/d', '/c', script], {
    detached: true,
    stdio: 'ignore',
    windowsHide: true
  }).unref()
}

export function setupAutoUpdater(getWindow: () => BrowserWindow | null) {
  if (handlersRegistered) return
  handlersRegistered = true

  // Limpiar bloqueos heredados (v0.3.43 usaba api.github.com y podía quedar blockedUntil).
  const legacy = readCooldownState()
  if (legacy.blockedUntil > 0) {
    writeCooldownState({ ...legacy, blockedUntil: 0 })
  }

  autoUpdater.autoDownload = false
  // Evitar instalación silenciosa al cerrar: el usuario elige “Instalar” y ve el Setup.
  autoUpdater.autoInstallOnAppQuit = false
  // Sin Cache-Control agresivo: fuerza más hits a GitHub y dispara rate limit (429).

  autoUpdater.on('checking-for-update', () => {
    sendStatus(getWindow(), { type: 'checking' })
  })

  autoUpdater.on('update-available', (info) => {
    const rawNotes =
      typeof info.releaseNotes === 'string'
        ? info.releaseNotes
        : Array.isArray(info.releaseNotes)
          ? info.releaseNotes.map((n) => (typeof n === 'string' ? n : n.note)).join('\n')
          : undefined
    const notes = rawNotes ? plainTextReleaseNotes(rawNotes) : undefined
    const releaseNotes =
      notes && !isAutoGeneratedChangelogOnly(notes) ? notes : undefined
    sendStatus(getWindow(), { type: 'available', version: info.version, releaseNotes })
  })

  autoUpdater.on('update-not-available', (info) => {
    sendStatus(getWindow(), { type: 'not-available', version: info.version })
  })

  autoUpdater.on('download-progress', (progress) => {
    sendStatus(getWindow(), {
      type: 'download-progress',
      percent: progress.percent,
      transferred: progress.transferred,
      total: progress.total
    })
  })

  autoUpdater.on('update-downloaded', (info) => {
    const event = info as UpdateDownloadedEvent
    if (event.downloadedFile) {
      downloadedInstallerPath = event.downloadedFile
    } else {
      downloadedInstallerPath = resolveInstallerPath(event)
    }
    sendStatus(getWindow(), { type: 'downloaded', version: event.version })
  })

  autoUpdater.on('error', (err) => {
    installingUpdate = false
    const rateLimited = isRateLimitError(err)
    if (rateLimited) markRateLimited()
    const retryAfterMs = rateLimited
      ? getCooldownRemainingMs() || RATE_LIMIT_COOLDOWN_MS
      : undefined
    sendStatus(getWindow(), {
      type: 'error',
      message: friendlyUpdateError(err),
      rateLimited: rateLimited || undefined,
      retryAfterMs
    })
  })

  ipcMain.handle('app:get-info', () => ({
    version: app.getVersion(),
    name: app.getName(),
    isPackaged: app.isPackaged,
    platform: process.platform,
    updatesConfigured: app.isPackaged
      ? existsSync(join(process.resourcesPath, 'app-update.yml'))
      : false
  }))

  ipcMain.handle('update:get-cooldown', (_event, payload?: { force?: boolean }) => {
    const retryAfterMs = getCooldownRemainingMs(Date.now(), { force: payload?.force })
    const state = readCooldownState()
    return {
      retryAfterMs,
      rateLimited: state.blockedUntil > Date.now(),
      releasesUrl: GITHUB_RELEASES_URL
    }
  })

  ipcMain.handle('update:clear-cooldown', () => {
    writeCooldownState({ lastCheckAt: 0, blockedUntil: 0 })
    return { ok: true as const }
  })

  ipcMain.handle('app:reset-database', async (_event, payload: { confirmacion?: string }) => {
    if (String(payload?.confirmacion ?? '').trim().toUpperCase() !== 'BORRAR') {
      return {
        ok: false as const,
        message: 'Para confirmar, enviá confirmacion: "BORRAR"'
      }
    }

    try {
      const { stopServer } = await import('../../server/index')
      const { closeDatabase, wipeDatabaseFiles } = await import('../../server/db')
      await stopServer()
      closeDatabase()
      wipeDatabaseFiles()
      app.relaunch()
      app.quit()
      return { ok: true as const }
    } catch (err) {
      return {
        ok: false as const,
        message: err instanceof Error ? err.message : 'No se pudo borrar la base de datos'
      }
    }
  })

  ipcMain.handle('update:check', async (_event, payload?: { force?: boolean }) => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    const force = Boolean(payload?.force)

    if (checkInFlight) {
      const message = 'Ya hay una búsqueda de actualizaciones en curso.'
      sendStatus(getWindow(), { type: 'error', message })
      return { ok: false as const, reason: 'error' as const, message }
    }

    const retryAfterMs = getCooldownRemainingMs(Date.now(), { force })
    if (retryAfterMs > 0) {
      const state = readCooldownState()
      const rateLimited = state.blockedUntil > Date.now()
      const message = cooldownMessage(retryAfterMs, rateLimited)
      sendStatus(getWindow(), {
        type: 'error',
        message,
        rateLimited: rateLimited || undefined,
        retryAfterMs
      })
      return {
        ok: false as const,
        reason: 'cooldown' as const,
        message,
        rateLimited,
        retryAfterMs
      }
    }

    configureAutoUpdaterFeed()
    checkInFlight = true
    markCheckAttempt()

    try {
      const result = await autoUpdater.checkForUpdates()
      clearRateLimitBlock()
      return { ok: true as const, updateInfo: result?.updateInfo?.version }
    } catch (err) {
      const rateLimited = isRateLimitError(err)
      if (rateLimited) markRateLimited()
      const waitMs = rateLimited
        ? getCooldownRemainingMs() || RATE_LIMIT_COOLDOWN_MS
        : getCooldownRemainingMs()
      const message = friendlyUpdateError(err)
      sendStatus(getWindow(), {
        type: 'error',
        message,
        rateLimited: rateLimited || undefined,
        retryAfterMs: waitMs > 0 ? waitMs : undefined
      })
      return {
        ok: false as const,
        reason: 'error' as const,
        message,
        rateLimited: rateLimited || undefined,
        retryAfterMs: waitMs > 0 ? waitMs : undefined
      }
    } finally {
      checkInFlight = false
    }
  })

  ipcMain.handle('update:download', async () => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    configureAutoUpdaterFeed()

    try {
      await autoUpdater.downloadUpdate()
      return { ok: true as const }
    } catch (err) {
      const rateLimited = isRateLimitError(err)
      if (rateLimited) markRateLimited()
      return {
        ok: false as const,
        message: friendlyUpdateError(err),
        rateLimited: rateLimited || undefined,
        retryAfterMs: rateLimited
          ? getCooldownRemainingMs() || RATE_LIMIT_COOLDOWN_MS
          : undefined
      }
    }
  })

  ipcMain.handle('update:install', async () => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    const installerPath = resolveInstallerPath()
    if (!installerPath) {
      return {
        ok: false as const,
        message:
          'No se encontró el instalador descargado. Buscá actualizaciones de nuevo o instalá el Setup desde GitHub Releases.'
      }
    }

    installingUpdate = true
    broadcastStatus({ type: 'installing' })

    try {
      const { shutdownNetworkServer } = await import('./network')
      await Promise.race([
        shutdownNetworkServer(),
        new Promise<void>((resolve) => setTimeout(resolve, 2000))
      ])
    } catch {
      /* ignore */
    }

    for (const win of BrowserWindow.getAllWindows()) {
      if (!win.isDestroyed()) win.destroy()
    }

    try {
      launchInstallerAfterAppExit(installerPath)
    } catch (err) {
      installingUpdate = false
      const message = friendlyUpdateError(err)
      broadcastStatus({ type: 'error', message })
      return { ok: false as const, message }
    }

    // Salir ya: el Setup se abre solo cuando Windows liberó ControlStock.exe
    setImmediate(() => {
      app.exit(0)
    })

    return { ok: true as const }
  })
}
