import { app, BrowserWindow, ipcMain } from 'electron'
import { spawn } from 'child_process'
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'fs'
import { join } from 'path'
import { autoUpdater, type UpdateDownloadedEvent } from 'electron-updater'
import { isAutoGeneratedChangelogOnly, plainTextReleaseNotes } from './releaseNotes'
import {
  compareSemver,
  fetchLatestReleaseVersion,
  normalizeReleaseVersion,
  releaseDownloadBaseUrl
} from '@/lib/githubLatestRelease'

const GITHUB_OWNER = 'JRNCarrizo'
const GITHUB_REPO = 'bodegaStock'
const GITHUB_RELEASES_URL = `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases`
/** Fallback si aún no conocemos el tag del release. */
const GENERIC_LATEST_URL = `https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest/download`

/** Evita doble clic seguido. */
const CHECK_DEBOUNCE_MS = 20 * 1000

export type UpdateStatusPayload =
  | { type: 'checking' }
  | { type: 'available'; version: string; releaseNotes?: string }
  | { type: 'not-available'; version: string }
  | { type: 'download-progress'; percent: number; transferred: number; total: number }
  | { type: 'downloaded'; version: string }
  | { type: 'installing'; version?: string }
  | {
      type: 'error'
      message: string
      rateLimited?: boolean
      retryAfterMs?: number
    }

type CooldownState = {
  lastCheckAt: number
}

function cooldownFilePath(): string {
  return join(app.getPath('userData'), 'update-github-cooldown.json')
}

function readCooldownState(): CooldownState {
  try {
    const raw = readFileSync(cooldownFilePath(), 'utf8')
    const parsed = JSON.parse(raw) as Partial<CooldownState & { blockedUntil?: number }>
    return {
      lastCheckAt: typeof parsed.lastCheckAt === 'number' ? parsed.lastCheckAt : 0
    }
  } catch {
    return { lastCheckAt: 0 }
  }
}

function writeCooldownState(state: CooldownState): void {
  try {
    writeFileSync(cooldownFilePath(), JSON.stringify(state), 'utf8')
  } catch {
    /* ignore disk errors */
  }
}

function clearCooldownFile(): void {
  try {
    unlinkSync(cooldownFilePath())
  } catch {
    /* ignore */
  }
  writeCooldownState({ lastCheckAt: 0 })
}

function getDebounceRemainingMs(now = Date.now(), opts?: { force?: boolean }): number {
  if (opts?.force) return 0
  const state = readCooldownState()
  return Math.max(0, state.lastCheckAt + CHECK_DEBOUNCE_MS - now)
}

function markCheckAttempt(now = Date.now()): void {
  writeCooldownState({ lastCheckAt: now })
}

function sendStatus(win: BrowserWindow | null, status: UpdateStatusPayload) {
  if (win && !win.isDestroyed()) {
    win.webContents.send('update-status', status)
  }
}

function broadcastStatus(status: UpdateStatusPayload) {
  for (const win of BrowserWindow.getAllWindows()) {
    sendStatus(win, status)
  }
}

let handlersRegistered = false
/** true mientras se lanza el NSIS: no cortar el proceso con app.exit */
let installingUpdate = false
/** Ruta del Setup descargado (para abrirlo con UI visible). */
let downloadedInstallerPath: string | null = null
/** Evita checks concurrentes a GitHub. */
let checkInFlight = false
/** Última versión disponible detectada (feed por tag concreto). */
let pendingUpdateVersion: string | null = null

export function isInstallingUpdate(): boolean {
  return installingUpdate
}

function configureAutoUpdaterFeed(version?: string | null): boolean {
  if (!app.isPackaged) return false

  const url =
    version && normalizeReleaseVersion(version)
      ? releaseDownloadBaseUrl(version)
      : GENERIC_LATEST_URL

  // Sin Authorization: si se reenvía token al CDN de GitHub, el redirect responde 403.
  autoUpdater.requestHeaders = {
    'User-Agent': 'ControlStock-Updater',
    Accept: '*/*'
  }
  autoUpdater.setFeedURL({
    provider: 'generic',
    url
  })
  return true
}

function friendlyUpdateError(err: unknown): string {
  const message = err instanceof Error ? err.message : String(err)

  if (message.includes('app-update.yml')) {
    return 'Esta versión no incluye actualizaciones automáticas. Descargá la última versión desde GitHub Releases e instalá manualmente.'
  }

  if (/\b429\b|Too Many Requests|rate limit exceeded/i.test(message)) {
    return 'GitHub limitó consultas desde esta red (HTTP 429). Esperá unos minutos o instalá el Setup a mano desde Releases.'
  }

  if (/\b403\b|Forbidden/i.test(message)) {
    return 'GitHub rechazó la descarga (HTTP 403). Suele fallar el redirect al CDN; probá de nuevo o instalá el Setup a mano desde Releases.'
  }

  if (message.includes('404') || message.includes('Not Found')) {
    return 'No se encontró un release compatible en GitHub. Descargá el instalador manualmente desde Releases.'
  }

  if (/ERR_HTTP2|HTTP2_PROTOCOL|net::ERR_/i.test(message)) {
    return 'Falló la descarga automática (red/GitHub). Probá de nuevo o instalá manualmente el Setup desde GitHub Releases.'
  }

  if (message.includes('<!DOCTYPE html>') || message.length > 280) {
    return 'No se pudo consultar actualizaciones en GitHub. Probá más tarde o instalá el Setup desde Releases.'
  }

  return message
}

function resolveInstallerPath(info?: UpdateDownloadedEvent): string | null {
  if (info?.downloadedFile && existsSync(info.downloadedFile)) {
    return info.downloadedFile
  }
  if (downloadedInstallerPath && existsSync(downloadedInstallerPath)) {
    return downloadedInstallerPath
  }
  const helper = (autoUpdater as unknown as { downloadedUpdateHelper?: { file?: string | null } })
    .downloadedUpdateHelper
  if (helper?.file && existsSync(helper.file)) return helper.file
  return null
}

/**
 * Cierra ControlStock y abre el Setup (evita el cartel "programa en uso").
 * El script sigue vivo aunque este proceso muera.
 */
function launchInstallerAfterAppExit(installerPath: string): void {
  const escaped = installerPath.replace(/"/g, '""')
  const comspec = process.env.ComSpec ?? 'cmd.exe'
  // Varias pasadas de taskkill + espera: si el .exe sigue vivo, NSIS se traba a mitad de barra.
  const script = [
    'taskkill /F /IM ControlStock.exe /T >nul 2>&1',
    'timeout /t 2 /nobreak >nul',
    'taskkill /F /IM ControlStock.exe /T >nul 2>&1',
    'timeout /t 2 /nobreak >nul',
    'taskkill /F /IM ControlStock.exe /T >nul 2>&1',
    'timeout /t 5 /nobreak >nul',
    `start "" "${escaped}"`
  ].join(' & ')
  spawn(comspec, ['/d', '/c', script], {
    detached: true,
    stdio: 'ignore',
    windowsHide: true
  }).unref()
}

async function closeLocalDbForUpdate(): Promise<void> {
  try {
    const { closeDatabase } = await import('../../server/db')
    closeDatabase()
  } catch {
    /* ignore */
  }
}

export function setupAutoUpdater(getWindow: () => BrowserWindow | null) {
  if (handlersRegistered) return
  handlersRegistered = true

  // Limpiar cooldowns viejos (v0.3.43–0.3.52 podían dejar blockedUntil de 30 min).
  clearCooldownFile()

  autoUpdater.autoDownload = false
  autoUpdater.autoInstallOnAppQuit = false
  // Diff + blockmap de GitHub a menudo falla/trunca; siempre bajamos el Setup completo.
  autoUpdater.disableDifferentialDownload = true

  autoUpdater.on('checking-for-update', () => {
    sendStatus(getWindow(), { type: 'checking' })
  })

  autoUpdater.on('update-available', (info) => {
    const rawNotes =
      typeof info.releaseNotes === 'string'
        ? info.releaseNotes
        : Array.isArray(info.releaseNotes)
          ? info.releaseNotes.map((n) => (typeof n === 'string' ? n : n.note)).join('\n')
          : undefined
    const notes = rawNotes ? plainTextReleaseNotes(rawNotes) : undefined
    const releaseNotes =
      notes && !isAutoGeneratedChangelogOnly(notes) ? notes : undefined
    sendStatus(getWindow(), { type: 'available', version: info.version, releaseNotes })
  })

  autoUpdater.on('update-not-available', (info) => {
    sendStatus(getWindow(), { type: 'not-available', version: info.version })
  })

  autoUpdater.on('download-progress', (progress) => {
    sendStatus(getWindow(), {
      type: 'download-progress',
      percent: progress.percent,
      transferred: progress.transferred,
      total: progress.total
    })
  })

  autoUpdater.on('update-downloaded', (info) => {
    const event = info as UpdateDownloadedEvent
    if (event.downloadedFile) {
      downloadedInstallerPath = event.downloadedFile
    } else {
      downloadedInstallerPath = resolveInstallerPath(event)
    }
    sendStatus(getWindow(), { type: 'downloaded', version: event.version })
  })

  autoUpdater.on('error', (err) => {
    installingUpdate = false
    sendStatus(getWindow(), {
      type: 'error',
      message: friendlyUpdateError(err)
    })
  })

  ipcMain.handle('app:get-info', () => ({
    version: app.getVersion(),
    name: app.getName(),
    isPackaged: app.isPackaged,
    platform: process.platform,
    updatesConfigured: app.isPackaged
      ? existsSync(join(process.resourcesPath, 'app-update.yml'))
      : false
  }))

  ipcMain.handle('update:get-cooldown', (_event, payload?: { force?: boolean }) => {
    const retryAfterMs = getDebounceRemainingMs(Date.now(), { force: payload?.force })
    return {
      retryAfterMs,
      rateLimited: false,
      releasesUrl: GITHUB_RELEASES_URL
    }
  })

  ipcMain.handle('update:clear-cooldown', () => {
    clearCooldownFile()
    return { ok: true as const }
  })

  ipcMain.handle('app:reset-database', async (_event, payload: { confirmacion?: string }) => {
    if (String(payload?.confirmacion ?? '').trim().toUpperCase() !== 'BORRAR') {
      return {
        ok: false as const,
        message: 'Para confirmar, enviá confirmacion: "BORRAR"'
      }
    }

    try {
      const { stopServer } = await import('../../server/index')
      const { closeDatabase, wipeDatabaseFiles } = await import('../../server/db')
      await stopServer()
      closeDatabase()
      wipeDatabaseFiles()
      app.relaunch()
      app.quit()
      return { ok: true as const }
    } catch (err) {
      return {
        ok: false as const,
        message: err instanceof Error ? err.message : 'No se pudo borrar la base de datos'
      }
    }
  })

  ipcMain.handle('update:check', async (_event, payload?: { force?: boolean }) => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    const force = Boolean(payload?.force)

    if (checkInFlight) {
      const message = 'Ya hay una búsqueda de actualizaciones en curso.'
      sendStatus(getWindow(), { type: 'error', message })
      return { ok: false as const, reason: 'error' as const, message }
    }

    if (force) {
      clearCooldownFile()
    }

    const retryAfterMs = getDebounceRemainingMs(Date.now(), { force })
    if (retryAfterMs > 0) {
      const secs = Math.max(1, Math.ceil(retryAfterMs / 1000))
      const message = `Esperá ~${secs} s antes de volver a buscar.`
      sendStatus(getWindow(), { type: 'error', message, retryAfterMs })
      return {
        ok: false as const,
        reason: 'cooldown' as const,
        message,
        rateLimited: false,
        retryAfterMs
      }
    }

    checkInFlight = true
    markCheckAttempt()
    sendStatus(getWindow(), { type: 'checking' })

    try {
      // Check propio (fetch + latest.yml): evita el bug de electron-updater con redirects de GitHub.
      const latestVersion = normalizeReleaseVersion(await fetchLatestReleaseVersion())
      const currentVersion = normalizeReleaseVersion(app.getVersion())

      if (compareSemver(latestVersion, currentVersion) > 0) {
        pendingUpdateVersion = latestVersion
        configureAutoUpdaterFeed(latestVersion)
        sendStatus(getWindow(), { type: 'available', version: latestVersion })
        return { ok: true as const, updateInfo: latestVersion }
      }

      pendingUpdateVersion = null
      sendStatus(getWindow(), { type: 'not-available', version: currentVersion })
      return { ok: true as const, updateInfo: currentVersion }
    } catch (err) {
      const message = friendlyUpdateError(err)
      sendStatus(getWindow(), { type: 'error', message })
      return {
        ok: false as const,
        reason: 'error' as const,
        message
      }
    } finally {
      checkInFlight = false
    }
  })

  ipcMain.handle('update:download', async () => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    clearCooldownFile()

    // Si no hicimos check antes, resolvemos el tag y apuntamos al release concreto.
    if (!pendingUpdateVersion) {
      try {
        pendingUpdateVersion = normalizeReleaseVersion(await fetchLatestReleaseVersion())
      } catch (err) {
        return {
          ok: false as const,
          message: `${friendlyUpdateError(err)} También podés abrir Releases e instalar el Setup a mano.`
        }
      }
    }

    configureAutoUpdaterFeed(pendingUpdateVersion)

    try {
      // Necesario para que electron-updater sepa qué archivo bajar desde el feed del tag.
      await autoUpdater.checkForUpdates()
      await autoUpdater.downloadUpdate()
      return { ok: true as const }
    } catch (firstErr) {
      // Un reintento suele salvar cortes de GitHub CDN / HTTP2.
      try {
        await new Promise((r) => setTimeout(r, 1500))
        configureAutoUpdaterFeed(pendingUpdateVersion)
        await autoUpdater.checkForUpdates()
        await autoUpdater.downloadUpdate()
        return { ok: true as const }
      } catch {
        return {
          ok: false as const,
          message: `${friendlyUpdateError(firstErr)} También podés abrir Releases e instalar el Setup a mano.`
        }
      }
    }
  })

  ipcMain.handle('update:open-releases', async () => {
    const { shell } = await import('electron')
    await shell.openExternal(GITHUB_RELEASES_URL)
    return { ok: true as const }
  })

  ipcMain.handle('update:install', async () => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    const installerPath = resolveInstallerPath()
    if (!installerPath) {
      return {
        ok: false as const,
        message:
          'No se encontró el instalador descargado. Buscá actualizaciones de nuevo o instalá el Setup desde GitHub Releases.'
      }
    }

    installingUpdate = true
    broadcastStatus({ type: 'installing' })

    try {
      const { shutdownNetworkServer } = await import('./network')
      await Promise.race([
        shutdownNetworkServer(),
        new Promise<void>((resolve) => setTimeout(resolve, 1500))
      ])
    } catch {
      /* ignore */
    }

    await closeLocalDbForUpdate()

    for (const win of BrowserWindow.getAllWindows()) {
      if (!win.isDestroyed()) win.destroy()
    }

    try {
      // Primero el script externo (mata + Setup); después salimos nosotros.
      launchInstallerAfterAppExit(installerPath)
    } catch (err) {
      installingUpdate = false
      const message = friendlyUpdateError(err)
      broadcastStatus({ type: 'error', message })
      return { ok: false as const, message }
    }

    // Salida dura: no esperar handles abiertos (servidor / sqlite).
    setTimeout(() => {
      app.exit(0)
    }, 300)
    setTimeout(() => {
      process.exit(0)
    }, 2500)

    return { ok: true as const }
  })
}
