import { app, BrowserWindow, ipcMain, shell } from 'electron'
import { spawn } from 'child_process'
import { existsSync } from 'fs'
import { join } from 'path'
import { autoUpdater, type UpdateDownloadedEvent } from 'electron-updater'
import { getAppIcon } from './icon'
import { isAutoGeneratedChangelogOnly, plainTextReleaseNotes } from './releaseNotes'

const GITHUB_OWNER = 'JRNCarrizo'
const GITHUB_REPO = 'bodegaStock'

export type UpdateStatusPayload =
  | { type: 'checking' }
  | { type: 'available'; version: string; releaseNotes?: string }
  | { type: 'not-available'; version: string }
  | { type: 'download-progress'; percent: number; transferred: number; total: number }
  | { type: 'downloaded'; version: string }
  | { type: 'installing'; version?: string }
  | { type: 'error'; message: string }

function sendStatus(win: BrowserWindow | null, status: UpdateStatusPayload) {
  if (win && !win.isDestroyed()) {
    win.webContents.send('update-status', status)
  }
}

function broadcastStatus(status: UpdateStatusPayload) {
  for (const win of BrowserWindow.getAllWindows()) {
    sendStatus(win, status)
  }
}

let handlersRegistered = false
/** true mientras se lanza el NSIS: no cortar el proceso con app.exit */
let installingUpdate = false
/** Ruta del Setup descargado (para abrirlo con UI visible). */
let downloadedInstallerPath: string | null = null

export function isInstallingUpdate(): boolean {
  return installingUpdate
}

function configureAutoUpdaterFeed(): boolean {
  if (!app.isPackaged) return false

  const updateYml = join(process.resourcesPath, 'app-update.yml')
  if (existsSync(updateYml)) return true

  autoUpdater.setFeedURL({
    provider: 'github',
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO
  })
  return true
}

function friendlyUpdateError(err: unknown): string {
  const message = err instanceof Error ? err.message : String(err)

  if (message.includes('app-update.yml')) {
    return 'Esta versión no incluye actualizaciones automáticas. Descargá la última versión desde GitHub Releases e instalá manualmente.'
  }

  if (/429|Too Many Requests|rate limit/i.test(message)) {
    return 'GitHub limitó las consultas por unos minutos (demasiados intentos). Esperá 10–30 min y volvé a buscar, o instalá el Setup a mano desde Releases.'
  }

  if (message.includes('404') || message.includes('Not Found')) {
    return 'No se encontró un release compatible en GitHub. Descargá el instalador manualmente desde Releases.'
  }

  if (/ERR_HTTP2|HTTP2_PROTOCOL|net::ERR_/i.test(message)) {
    return 'Falló la descarga automática (red/GitHub). Probá de nuevo o instalá manualmente el Setup desde GitHub Releases.'
  }

  // Evitar pegar HTML completo de GitHub en la UI.
  if (message.includes('<!DOCTYPE html>') || message.length > 280) {
    return 'No se pudo consultar actualizaciones en GitHub. Probá más tarde o instalá el Setup desde Releases.'
  }

  return message
}

function resolveInstallerPath(info?: UpdateDownloadedEvent): string | null {
  if (info?.downloadedFile && existsSync(info.downloadedFile)) {
    return info.downloadedFile
  }
  if (downloadedInstallerPath && existsSync(downloadedInstallerPath)) {
    return downloadedInstallerPath
  }
  const helper = (autoUpdater as unknown as { downloadedUpdateHelper?: { file?: string | null } })
    .downloadedUpdateHelper
  if (helper?.file && existsSync(helper.file)) return helper.file
  return null
}

/**
 * Abre el Setup como ventana normal (visible).
 * No usamos quitAndInstall(--updated): ese modo suele correr casi oculto (solo cursor de espera).
 */
function launchVisibleInstaller(installerPath: string): void {
  const child = spawn(installerPath, [], {
    detached: true,
    stdio: 'ignore',
    windowsHide: false
  })
  child.unref()
}

function showInstallSplash(): BrowserWindow {
  const icon = getAppIcon()
  const splash = new BrowserWindow({
    width: 460,
    height: 260,
    resizable: false,
    maximizable: false,
    minimizable: false,
    alwaysOnTop: true,
    center: true,
    autoHideMenuBar: true,
    title: 'ControlStock — Actualizando',
    icon,
    show: true,
    webPreferences: {
      sandbox: true,
      contextIsolation: true,
      nodeIntegration: false
    }
  })

  const html = `<!DOCTYPE html>
<html lang="es"><head><meta charset="utf-8" />
<style>
  html,body{margin:0;height:100%;font-family:Segoe UI,system-ui,sans-serif;background:#0f172a;color:#f8fafc}
  main{display:flex;flex-direction:column;justify-content:center;align-items:center;height:100%;padding:28px;text-align:center;gap:12px;box-sizing:border-box}
  h1{margin:0;font-size:18px;font-weight:700}
  p{margin:0;font-size:13px;line-height:1.45;color:#cbd5e1;max-width:36ch}
  .bar{width:100%;max-width:280px;height:8px;border-radius:999px;background:#1e293b;overflow:hidden;margin-top:8px}
  .bar>i{display:block;height:100%;width:40%;border-radius:999px;background:#3b82f6;animation:slide 1.1s ease-in-out infinite}
  @keyframes slide{0%{transform:translateX(-120%)}100%{transform:translateX(320%)}}
</style></head>
<body><main>
  <h1>Abriendo el instalador…</h1>
  <p>En unos segundos vas a ver la ventana del Setup de Windows con la <strong>barra de progreso</strong>. Completá los pasos ahí; al final podés abrir ControlStock.</p>
  <div class="bar" aria-hidden="true"><i></i></div>
</main></body></html>`

  void splash.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`)
  splash.moveTop()
  splash.focus()
  return splash
}

export function setupAutoUpdater(getWindow: () => BrowserWindow | null) {
  if (handlersRegistered) return
  handlersRegistered = true

  autoUpdater.autoDownload = false
  // Evitar instalación silenciosa al cerrar: el usuario elige “Instalar” y ve el Setup.
  autoUpdater.autoInstallOnAppQuit = false
  // Sin Cache-Control agresivo: fuerza más hits a GitHub y dispara rate limit (429).

  autoUpdater.on('checking-for-update', () => {
    sendStatus(getWindow(), { type: 'checking' })
  })

  autoUpdater.on('update-available', (info) => {
    const rawNotes =
      typeof info.releaseNotes === 'string'
        ? info.releaseNotes
        : Array.isArray(info.releaseNotes)
          ? info.releaseNotes.map((n) => (typeof n === 'string' ? n : n.note)).join('\n')
          : undefined
    const notes = rawNotes ? plainTextReleaseNotes(rawNotes) : undefined
    const releaseNotes =
      notes && !isAutoGeneratedChangelogOnly(notes) ? notes : undefined
    sendStatus(getWindow(), { type: 'available', version: info.version, releaseNotes })
  })

  autoUpdater.on('update-not-available', (info) => {
    sendStatus(getWindow(), { type: 'not-available', version: info.version })
  })

  autoUpdater.on('download-progress', (progress) => {
    sendStatus(getWindow(), {
      type: 'download-progress',
      percent: progress.percent,
      transferred: progress.transferred,
      total: progress.total
    })
  })

  autoUpdater.on('update-downloaded', (info) => {
    const event = info as UpdateDownloadedEvent
    if (event.downloadedFile) {
      downloadedInstallerPath = event.downloadedFile
    } else {
      downloadedInstallerPath = resolveInstallerPath(event)
    }
    sendStatus(getWindow(), { type: 'downloaded', version: event.version })
  })

  autoUpdater.on('error', (err) => {
    installingUpdate = false
    sendStatus(getWindow(), { type: 'error', message: friendlyUpdateError(err) })
  })

  ipcMain.handle('app:get-info', () => ({
    version: app.getVersion(),
    name: app.getName(),
    isPackaged: app.isPackaged,
    platform: process.platform,
    updatesConfigured: app.isPackaged
      ? existsSync(join(process.resourcesPath, 'app-update.yml'))
      : false
  }))

  ipcMain.handle('app:reset-database', async (_event, payload: { confirmacion?: string }) => {
    if (String(payload?.confirmacion ?? '').trim().toUpperCase() !== 'BORRAR') {
      return {
        ok: false as const,
        message: 'Para confirmar, enviá confirmacion: "BORRAR"'
      }
    }

    try {
      const { stopServer } = await import('../../server/index')
      const { closeDatabase, wipeDatabaseFiles } = await import('../../server/db')
      await stopServer()
      closeDatabase()
      wipeDatabaseFiles()
      app.relaunch()
      app.quit()
      return { ok: true as const }
    } catch (err) {
      return {
        ok: false as const,
        message: err instanceof Error ? err.message : 'No se pudo borrar la base de datos'
      }
    }
  })

  ipcMain.handle('update:check', async () => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    configureAutoUpdaterFeed()

    try {
      const result = await autoUpdater.checkForUpdates()
      return { ok: true as const, updateInfo: result?.updateInfo?.version }
    } catch (err) {
      return {
        ok: false as const,
        reason: 'error' as const,
        message: friendlyUpdateError(err)
      }
    }
  })

  ipcMain.handle('update:download', async () => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    configureAutoUpdaterFeed()

    try {
      await autoUpdater.downloadUpdate()
      return { ok: true as const }
    } catch (err) {
      return {
        ok: false as const,
        message: friendlyUpdateError(err)
      }
    }
  })

  ipcMain.handle('update:install', async () => {
    if (!app.isPackaged) {
      return { ok: false as const, reason: 'dev' as const }
    }

    const installerPath = resolveInstallerPath()
    if (!installerPath) {
      return {
        ok: false as const,
        message:
          'No se encontró el instalador descargado. Buscá actualizaciones de nuevo o instalá el Setup desde GitHub Releases.'
      }
    }

    installingUpdate = true
    broadcastStatus({ type: 'installing' })
    showInstallSplash()

    try {
      const { shutdownNetworkServer } = await import('./network')
      await Promise.race([
        shutdownNetworkServer(),
        new Promise<void>((resolve) => setTimeout(resolve, 2000))
      ])
    } catch {
      /* ignore */
    }

    try {
      launchVisibleInstaller(installerPath)
    } catch (err) {
      try {
        await shell.openPath(installerPath)
      } catch (openErr) {
        installingUpdate = false
        const message = friendlyUpdateError(openErr ?? err)
        broadcastStatus({ type: 'error', message })
        return { ok: false as const, message }
      }
    }

    // Liberar archivos para que el Setup pueda reemplazarlos; el progreso se ve en el Setup.
    setTimeout(() => {
      app.quit()
    }, 1200)

    return { ok: true as const }
  })
}
