import { useCallback, useEffect, useMemo, useState } from 'react'
import QRCode from 'qrcode'
import {
  ArrowLeftRight,
  Check,
  ChevronDown,
  ClipboardCheck,
  Cloud,
  Copy,
  Database,
  Download,
  Loader2,
  RefreshCw,
  Server,
  Smartphone,
  Wifi
} from 'lucide-react'
import { useAuth } from '@/context/AuthContext'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Card, CardBody } from '@/components/ui/Card'
import { AppCopyrightFooter } from '@/components/AppCopyrightFooter'
import { cn, api as httpApi, getApiUrl, setApiUrl } from '@/lib/utils'
import {
  loadConnectionMode,
  loadSavedServerUrl,
  saveConnectionMode,
  saveServerUrl,
  testServerConnection,
  type ConnectionMode
} from '@/lib/nativeServer'
import { isAutoGeneratedChangelogOnly, plainTextReleaseNotes } from '@/lib/releaseNotes'
import type {
  AppInfo,
  NetworkConfig,
  NetworkRuntimeInfo,
  UpdateStatusPayload
} from '@/vite-env'

type UpdatePhase =
  | 'idle'
  | 'checking'
  | 'available'
  | 'not-available'
  | 'downloading'
  | 'downloaded'
  | 'installing'
  | 'error'
  | 'dev-mode'

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function displayRemoteHost(host: string): string {
  const trimmed = host.trim()
  return trimmed === '127.0.0.1' ? '' : trimmed
}

function parseServerConnection(raw: string): { host: string; port?: string } | null {
  const value = raw.trim()
  if (!value) return null

  try {
    const url = value.includes('://') ? new URL(value) : new URL(`http://${value}`)
    const host = url.hostname
    const port = url.port || undefined
    if (!host) return null
    return { host, port }
  } catch {
    const match = value.match(/^([\d.]+)(?::(\d+))?$/)
    if (!match) return null
    return { host: match[1], port: match[2] }
  }
}

function StatusPill({
  tone,
  children
}: {
  tone: 'success' | 'warning' | 'neutral' | 'brand'
  children: React.ReactNode
}) {
  const styles = {
    success: 'bg-emerald-50 text-emerald-800 ring-emerald-100',
    warning: 'bg-amber-50 text-amber-800 ring-amber-100',
    neutral: 'bg-slate-100 text-slate-700 ring-surface-border',
    brand: 'bg-brand-50 text-brand-800 ring-brand-100'
  }
  return (
    <span
      className={cn(
        'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ring-1',
        styles[tone]
      )}
    >
      {children}
    </span>
  )
}

function ModeOption({
  active,
  icon: Icon,
  title,
  description,
  onClick
}: {
  active: boolean
  icon: typeof Server
  title: string
  description: string
  onClick: () => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'rounded-xl border px-4 py-3.5 text-left transition-all',
        active
          ? 'border-brand-500 bg-brand-50 shadow-sm ring-2 ring-brand-500/20'
          : 'border-surface-border bg-white hover:border-slate-300 hover:bg-slate-50/80'
      )}
    >
      <div className="flex items-center gap-2.5">
        <div
          className={cn(
            'flex h-9 w-9 shrink-0 items-center justify-center rounded-lg',
            active ? 'bg-brand-600 text-white' : 'bg-slate-100 text-slate-600'
          )}
        >
          <Icon className="h-4 w-4" />
        </div>
        <span className="text-sm font-semibold text-slate-900">{title}</span>
      </div>
      <p className="mt-2 pl-[2.875rem] text-xs leading-relaxed text-slate-500">{description}</p>
    </button>
  )
}

export function ConfiguracionPage() {
  const api = window.bodegaStock
  const { user } = useAuth()
  const [appInfo, setAppInfo] = useState<AppInfo | null>(null)
  const [networkInfo, setNetworkInfo] = useState<NetworkRuntimeInfo | null>(null)
  const [connectionMode, setConnectionMode] = useState<ConnectionMode>('local')
  const [cloudUrl, setCloudUrl] = useState('')
  const [cloudTest, setCloudTest] = useState<'idle' | 'testing' | 'ok' | 'fail'>('idle')
  const [cloudMessage, setCloudMessage] = useState('')
  const [savingCloud, setSavingCloud] = useState(false)
  const [cloudPanelOpen, setCloudPanelOpen] = useState(false)
  const [cloudLive, setCloudLive] = useState(false)
  const [migPanelOpen, setMigPanelOpen] = useState(false)
  const [mode, setMode] = useState<NetworkConfig['mode']>('server')
  const [remoteHost, setRemoteHost] = useState('')
  const [port, setPort] = useState('3847')
  const [connectionTest, setConnectionTest] = useState<'idle' | 'testing' | 'ok' | 'fail'>('idle')
  const [connectionMessage, setConnectionMessage] = useState('')
  const [savingNetwork, setSavingNetwork] = useState(false)
  const [copiedUrl, setCopiedUrl] = useState('')
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null)
  const [cloudQrDataUrl, setCloudQrDataUrl] = useState<string | null>(null)
  const [phase, setPhase] = useState<UpdatePhase>('idle')
  const [availableVersion, setAvailableVersion] = useState('')
  const [releaseNotes, setReleaseNotes] = useState('')
  const [downloadPercent, setDownloadPercent] = useState(0)
  const [downloadDetail, setDownloadDetail] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [dobleVerificacionRetornos, setDobleVerificacionRetornos] = useState(true)
  const [dobleVerificacionMovimientos, setDobleVerificacionMovimientos] = useState(true)
  const [loadingOpCfg, setLoadingOpCfg] = useState(true)
  const [savingRetornosCfg, setSavingRetornosCfg] = useState(false)
  const [savingMovimientosCfg, setSavingMovimientosCfg] = useState(false)
  const [opCfgError, setOpCfgError] = useState('')
  const [opCfgSaved, setOpCfgSaved] = useState<'retornos' | 'movimientos' | null>(null)
  const [showResetStock, setShowResetStock] = useState(false)
  const [resetConfirmacion, setResetConfirmacion] = useState('')
  const [resettingStock, setResettingStock] = useState(false)
  const [resetStockError, setResetStockError] = useState('')
  const [resetStockOk, setResetStockOk] = useState('')
  const [wipeConfirmacion, setWipeConfirmacion] = useState('')
  const [wipingDb, setWipingDb] = useState(false)
  const [wipeDbError, setWipeDbError] = useState('')
  const [migConfirmacion, setMigConfirmacion] = useState('')
  const [migrating, setMigrating] = useState(false)
  const [migError, setMigError] = useState('')
  const [migOk, setMigOk] = useState('')
  const [migCounts, setMigCounts] = useState<Record<string, number> | null>(null)

  const primaryConnectionUrl = useMemo(
    () => networkInfo?.connectionUrls[0] ?? '',
    [networkInfo?.connectionUrls]
  )

  const loadNetworkInfo = useCallback(async () => {
    if (!api?.getNetworkInfo) return
    const info = await api.getNetworkInfo()
    setNetworkInfo(info)
    setMode(info.config.mode)
    setRemoteHost(displayRemoteHost(info.config.remoteHost))
    setPort(String(info.config.port))
  }, [api])

  useEffect(() => {
    void loadNetworkInfo()
  }, [loadNetworkInfo])

  useEffect(() => {
    void (async () => {
      const [modeSaved, urlSaved] = await Promise.all([loadConnectionMode(), loadSavedServerUrl()])
      setConnectionMode(modeSaved)
      if (urlSaved?.startsWith('https://')) setCloudUrl(urlSaved)
      else if (modeSaved === 'cloud' && urlSaved) setCloudUrl(urlSaved)

      if (modeSaved === 'cloud' && urlSaved) {
        setCloudPanelOpen(false)
        const result = await testServerConnection(urlSaved)
        setCloudLive(result.ok)
        setCloudTest(result.ok ? 'ok' : 'fail')
        if (result.ok) {
          setCloudMessage(
            result.version
              ? `Conectado a ControlStock v${result.version}`
              : 'Conexión activa con la nube'
          )
        } else {
          setCloudMessage(result.message)
        }
      } else if (modeSaved === 'cloud') {
        setCloudPanelOpen(true)
        setCloudLive(false)
      }
    })()
  }, [])

  async function probarNube() {
    setCloudTest('testing')
    setCloudMessage('')
    setCloudLive(false)
    const result = await testServerConnection(cloudUrl.trim())
    if (result.ok) {
      setCloudTest('ok')
      setCloudLive(false) // aún no guardada en esta acción
      setCloudMessage(
        result.version
          ? `Conectado a ControlStock v${result.version}`
          : 'Conexión exitosa con la nube'
      )
      return
    }
    setCloudTest('fail')
    setCloudMessage(result.message)
  }

  async function guardarNube() {
    setSavingCloud(true)
    setCloudMessage('')
    try {
      const result = await testServerConnection(cloudUrl.trim())
      if (!result.ok) {
        setCloudTest('fail')
        setCloudLive(false)
        setCloudMessage(result.message)
        return
      }
      const saved = await saveServerUrl(cloudUrl.trim())
      await saveConnectionMode('cloud')
      setApiUrl(saved)
      setCloudUrl(saved)
      setConnectionMode('cloud')
      setCloudTest('ok')
      setCloudLive(true)
      setCloudPanelOpen(false)
      setCloudMessage(
        result.version
          ? `Guardado y conectado · ControlStock v${result.version}`
          : 'URL guardada y conectada a la nube'
      )
    } finally {
      setSavingCloud(false)
    }
  }

  async function volverALocal() {
    await saveConnectionMode('local')
    setConnectionMode('local')
    setCloudTest('idle')
    setCloudMessage('')
    setCloudLive(false)
    setCloudPanelOpen(false)
    setMigPanelOpen(false)
    if (api?.getNetworkInfo) {
      const info = await api.getNetworkInfo()
      setApiUrl(info.apiUrl)
    }
  }
  useEffect(() => {
    void (async () => {
      setLoadingOpCfg(true)
      setOpCfgError('')
      try {
        const [retornos, movimientos] = await Promise.all([
          httpApi<{ doble_verificacion: boolean }>('/api/configuracion/retornos'),
          httpApi<{ doble_verificacion: boolean }>('/api/configuracion/movimientos')
        ])
        setDobleVerificacionRetornos(retornos.doble_verificacion)
        setDobleVerificacionMovimientos(movimientos.doble_verificacion)
      } catch (err) {
        setOpCfgError(
          err instanceof Error ? err.message : 'No se pudo cargar la configuración de operación'
        )
      } finally {
        setLoadingOpCfg(false)
      }
    })()
  }, [])

  async function guardarRetornosCfg(next: boolean) {
    setSavingRetornosCfg(true)
    setOpCfgError('')
    setOpCfgSaved(null)
    const prev = dobleVerificacionRetornos
    setDobleVerificacionRetornos(next)
    try {
      const cfg = await httpApi<{ doble_verificacion: boolean }>('/api/configuracion/retornos', {
        method: 'PUT',
        body: JSON.stringify({ doble_verificacion: next })
      })
      setDobleVerificacionRetornos(cfg.doble_verificacion)
      setOpCfgSaved('retornos')
      setTimeout(() => setOpCfgSaved(null), 2500)
    } catch (err) {
      setDobleVerificacionRetornos(prev)
      setOpCfgError(
        err instanceof Error ? err.message : 'No se pudo guardar la configuración de retornos'
      )
    } finally {
      setSavingRetornosCfg(false)
    }
  }

  async function guardarMovimientosCfg(next: boolean) {
    setSavingMovimientosCfg(true)
    setOpCfgError('')
    setOpCfgSaved(null)
    const prev = dobleVerificacionMovimientos
    setDobleVerificacionMovimientos(next)
    try {
      const cfg = await httpApi<{ doble_verificacion: boolean }>('/api/configuracion/movimientos', {
        method: 'PUT',
        body: JSON.stringify({ doble_verificacion: next })
      })
      setDobleVerificacionMovimientos(cfg.doble_verificacion)
      setOpCfgSaved('movimientos')
      setTimeout(() => setOpCfgSaved(null), 2500)
    } catch (err) {
      setDobleVerificacionMovimientos(prev)
      setOpCfgError(
        err instanceof Error ? err.message : 'No se pudo guardar la configuración de movimientos'
      )
    } finally {
      setSavingMovimientosCfg(false)
    }
  }

  async function resetearStockACero() {
    if (resetConfirmacion.trim().toUpperCase() !== 'CERO') {
      setResetStockError('Escribí CERO para confirmar.')
      return
    }
    setResettingStock(true)
    setResetStockError('')
    setResetStockOk('')
    try {
      const res = await httpApi<{
        ok: boolean
        antes: { lineas: number; sectores_con_stock: number; total_cajas: number }
        lineas_borradas: number
      }>('/api/configuracion/reset-stock', {
        method: 'POST',
        body: JSON.stringify({ confirmacion: 'CERO' })
      })
      setResetStockOk(
        `Stock en cero. Se quitaron ${res.lineas_borradas} líneas (${res.antes.total_cajas} cajas en total). Productos y sectores se mantienen.`
      )
      setResetConfirmacion('')
      setShowResetStock(false)
    } catch (err) {
      setResetStockError(err instanceof Error ? err.message : 'No se pudo poner el stock en cero')
    } finally {
      setResettingStock(false)
    }
  }

  async function borrarBaseYReiniciar() {
    if (wipeConfirmacion.trim().toUpperCase() !== 'BORRAR') {
      setWipeDbError('Escribí BORRAR para confirmar.')
      return
    }
    if (!api?.resetDatabase) {
      setWipeDbError('Esta acción solo está disponible en la app de escritorio.')
      return
    }
    setWipingDb(true)
    setWipeDbError('')
    try {
      const res = await api.resetDatabase('BORRAR')
      if (!res.ok) {
        setWipeDbError(res.message ?? 'No se pudo borrar la base de datos')
        setWipingDb(false)
      }
      // Si ok, la app se reinicia sola
    } catch (err) {
      setWipeDbError(err instanceof Error ? err.message : 'No se pudo borrar la base de datos')
      setWipingDb(false)
    }
  }

  useEffect(() => {
    if (!primaryConnectionUrl || mode !== 'server') {
      setQrDataUrl(null)
      return
    }

    void QRCode.toDataURL(primaryConnectionUrl, {
      margin: 1,
      width: 180,
      color: { dark: '#0f172a', light: '#ffffff' }
    }).then(setQrDataUrl)
  }, [primaryConnectionUrl, mode])

  const cloudQrUrl = useMemo(() => {
    if (connectionMode !== 'cloud') return ''
    const raw = (cloudUrl || getApiUrl()).trim().replace(/\/$/, '')
    return raw.startsWith('https://') ? raw : ''
  }, [connectionMode, cloudUrl])

  useEffect(() => {
    if (!cloudQrUrl || !cloudLive) {
      setCloudQrDataUrl(null)
      return
    }
    void QRCode.toDataURL(cloudQrUrl, {
      margin: 1,
      width: 180,
      color: { dark: '#0f172a', light: '#ffffff' }
    }).then(setCloudQrDataUrl)
  }, [cloudQrUrl, cloudLive])

  const handleStatus = useCallback((status: UpdateStatusPayload) => {
    switch (status.type) {
      case 'checking':
        setPhase('checking')
        setErrorMessage('')
        break
      case 'available':
        setPhase('available')
        setAvailableVersion(status.version)
        {
          const notes = plainTextReleaseNotes(status.releaseNotes)
          setReleaseNotes(notes && !isAutoGeneratedChangelogOnly(notes) ? notes : '')
        }
        break
      case 'not-available':
        setPhase('not-available')
        setAvailableVersion(status.version)
        break
      case 'download-progress':
        setPhase('downloading')
        setDownloadPercent(Math.min(100, Math.max(0, Math.round(status.percent))))
        setDownloadDetail(`${formatBytes(status.transferred)} / ${formatBytes(status.total)}`)
        break
      case 'downloaded':
        setPhase('downloaded')
        setAvailableVersion(status.version)
        break
      case 'installing':
        setPhase('installing')
        break
      case 'error':
        setPhase('error')
        setErrorMessage(status.message)
        break
    }
  }, [])

  useEffect(() => {
    if (!api?.getAppInfo) return
    void api.getAppInfo().then(setAppInfo)
  }, [api])

  useEffect(() => {
    if (!api?.onUpdateStatus) return
    return api.onUpdateStatus(handleStatus)
  }, [api, handleStatus])

  async function buscarActualizaciones() {
    if (!api?.checkForUpdates) {
      setPhase('dev-mode')
      return
    }

    setPhase('checking')
    setErrorMessage('')

    const result = await api.checkForUpdates()
    if (result.reason === 'dev') {
      setPhase('dev-mode')
      return
    }
    if (!result.ok) {
      setPhase('error')
      setErrorMessage(
        result.message ??
          'No se pudo comprobar actualizaciones. Verifique que la app esté instalada y que exista un servidor de releases configurado.'
      )
    }
  }

  async function descargarActualizacion() {
    if (!api?.downloadUpdate) return
    setPhase('downloading')
    setDownloadPercent(0)
    const result = await api.downloadUpdate()
    if (!result.ok) {
      setPhase('error')
      setErrorMessage(result.message ?? 'Error al descargar la actualización')
    }
  }

  async function instalarActualizacion() {
    if (!api?.installUpdate) return
    await api.installUpdate()
  }

  async function probarConexion() {
    if (!api?.testNetworkConnection) return

    setConnectionTest('testing')
    setConnectionMessage('')

    const result = await api.testNetworkConnection(remoteHost.trim(), Number(port) || 3847)
    if (result.ok) {
      setConnectionTest('ok')
      setConnectionMessage(
        result.version
          ? `Conectado a ${result.app ?? 'ControlStock'} v${result.version}`
          : 'Conexión exitosa con el servidor'
      )
      return
    }

    setConnectionTest('fail')
    setConnectionMessage(result.message ?? 'No se pudo conectar')
  }

  async function guardarRed() {
    if (!api?.applyNetworkConfig) return

    const host = remoteHost.trim()
    if (mode === 'client' && !host) {
      setConnectionTest('fail')
      setConnectionMessage(
        'Ingresá la IP del servidor (no uses 127.0.0.1 salvo que el servidor sea esta misma PC).'
      )
      return
    }

    setSavingNetwork(true)
    try {
      await saveConnectionMode('local')
      setConnectionMode('local')
      await api.applyNetworkConfig({
        mode,
        remoteHost: host || '127.0.0.1',
        port: Number(port) || 3847
      })
    } finally {
      setSavingNetwork(false)
    }
  }

  async function migrarLocalANube() {
    setMigError('')
    setMigOk('')
    setMigCounts(null)
    if (connectionMode !== 'cloud') {
      setMigError('Primero activá y guardá el modo Nube (Railway).')
      return
    }
    if (!getApiUrl().startsWith('https://')) {
      setMigError('La API actual no parece ser la nube (HTTPS). Guardá la URL de Railway.')
      return
    }
    if (migConfirmacion.trim() !== 'MIGRAR') {
      setMigError('Escribí MIGRAR para confirmar.')
      return
    }
    if (!api?.exportLocalDatabase) {
      setMigError('La migración requiere la aplicación de escritorio.')
      return
    }

    setMigrating(true)
    try {
      const exported = await api.exportLocalDatabase()
      if (!exported.ok) {
        setMigError(exported.message || 'No se pudo leer la base local')
        return
      }
      setMigCounts(exported.counts)
      const result = await httpApi<{ ok: boolean; message?: string; imported?: Record<string, number> }>(
        '/api/migracion/import',
        {
          method: 'POST',
          body: JSON.stringify({ dump: exported.dump, confirmacion: 'MIGRAR' }),
          timeoutMs: 120000,
        }
      )
      setMigOk(result.message || 'Migración completa. Cerrá sesión y volvé a entrar.')
      if (result.imported) setMigCounts(result.imported)
      setMigConfirmacion('')
    } catch (err) {
      setMigError(err instanceof Error ? err.message : 'Error al migrar')
    } finally {
      setMigrating(false)
    }
  }

  async function copiarUrl(url: string) {
    await navigator.clipboard.writeText(url)
    setCopiedUrl(url)
    setTimeout(() => setCopiedUrl(''), 2000)
  }

  const isElectron = Boolean(api?.getAppInfo)
  const isPackaged = appInfo?.isPackaged ?? false
  const hasNetworkConfig = Boolean(api?.applyNetworkConfig)

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <section>
        <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Sistema</p>
        <h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
          Configuración
        </h1>
        <p className="mt-2 max-w-xl text-sm leading-relaxed text-slate-500">
          Red local o nube (Railway), actualizaciones, reglas de operación e información de la
          aplicación.
        </p>
      </section>

      <Card className="overflow-hidden shadow-panel">
        <div className="border-b border-brand-100 bg-gradient-to-r from-brand-50/80 via-white to-white px-5 py-4 sm:px-6">
          <div className="flex items-start gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-600 text-white shadow-sm">
              <Wifi className="h-5 w-5" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-900">Red y conexión</h2>
              <p className="mt-0.5 text-sm text-slate-500">
                Red local (PC servidor) o servidor en la nube (Railway)
              </p>
            </div>
          </div>
        </div>

        <CardBody className="space-y-5 p-5 sm:p-6">
          <div className="grid gap-3 sm:grid-cols-2">
            <ModeOption
              active={connectionMode === 'local'}
              icon={Wifi}
              title="Red local"
              description="PC servidor en la LAN, como hasta ahora."
              onClick={() => {
                if (connectionMode === 'cloud') void volverALocal()
                else setConnectionMode('local')
              }}
            />
            <ModeOption
              active={connectionMode === 'cloud'}
              icon={Cloud}
              title="Nube (Railway)"
              description="API remota por HTTPS. Datos en el servidor cloud."
              onClick={() => {
                setConnectionMode('cloud')
                if (!cloudLive) setCloudPanelOpen(true)
              }}
            />
          </div>

          {connectionMode === 'cloud' && (
            <div className="overflow-hidden rounded-xl border border-surface-border bg-slate-50/80">
              <button
                type="button"
                className="flex w-full items-center gap-3 px-4 py-3.5 text-left transition hover:bg-white/70 sm:px-5"
                onClick={() => setCloudPanelOpen((open) => !open)}
                aria-expanded={cloudPanelOpen}
              >
                <div className="min-w-0 flex-1 space-y-1.5">
                  <div className="flex flex-wrap items-center gap-2">
                    {cloudLive ? (
                      <StatusPill tone="success">Conectada y guardada</StatusPill>
                    ) : cloudUrl.trim() && connectionMode === 'cloud' ? (
                      <StatusPill tone="warning">URL pendiente de guardar/probar</StatusPill>
                    ) : (
                      <StatusPill tone="neutral">Sin URL de nube</StatusPill>
                    )}
                    {cloudTest === 'ok' && !cloudLive && (
                      <StatusPill tone="brand">Prueba OK — guardá para activar</StatusPill>
                    )}
                  </div>
                  {(cloudUrl || getApiUrl().startsWith('https://')) && (
                    <p className="truncate font-mono text-xs text-slate-600">
                      {cloudUrl || getApiUrl()}
                    </p>
                  )}
                  {cloudLive && cloudMessage && !cloudPanelOpen && (
                    <p className="text-xs text-emerald-700">{cloudMessage}</p>
                  )}
                </div>
                <ChevronDown
                  className={cn(
                    'h-5 w-5 shrink-0 text-slate-400 transition-transform',
                    cloudPanelOpen && 'rotate-180'
                  )}
                />
              </button>

              {cloudPanelOpen && (
                <div className="space-y-4 border-t border-surface-border px-4 py-4 sm:px-5">
                  <p className="text-sm text-slate-600">
                    Pegá la URL pública de Railway (sin barra final).
                  </p>
                  <Input
                    label="URL del servidor cloud"
                    value={cloudUrl}
                    onChange={(e) => {
                      setCloudUrl(e.target.value.trim())
                      setCloudTest('idle')
                      setCloudLive(false)
                    }}
                    placeholder="https://….up.railway.app"
                    className="rounded-xl shadow-sm"
                    autoComplete="off"
                  />
                  <div className="flex flex-wrap gap-2">
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      className="rounded-xl"
                      disabled={cloudTest === 'testing' || !cloudUrl.trim()}
                      onClick={() => void probarNube()}
                    >
                      {cloudTest === 'testing' ? (
                        <>
                          <Loader2 className="h-4 w-4 animate-spin" />
                          Probando…
                        </>
                      ) : (
                        'Probar conexión'
                      )}
                    </Button>
                    <Button
                      type="button"
                      size="sm"
                      className="rounded-xl"
                      disabled={savingCloud || !cloudUrl.trim()}
                      onClick={() => void guardarNube()}
                    >
                      {savingCloud ? (
                        <>
                          <Loader2 className="h-4 w-4 animate-spin" />
                          Guardando…
                        </>
                      ) : (
                        'Guardar nube'
                      )}
                    </Button>
                  </div>
                  {cloudTest === 'ok' && cloudMessage && (
                    <p className="rounded-xl bg-emerald-50 px-3 py-2.5 text-sm text-emerald-800 ring-1 ring-emerald-100">
                      {cloudMessage}
                    </p>
                  )}
                  {cloudTest === 'fail' && cloudMessage && (
                    <p className="rounded-xl bg-red-50 px-3 py-2.5 text-sm text-red-800 ring-1 ring-red-100">
                      {cloudMessage}
                    </p>
                  )}
                </div>
              )}

              {cloudLive && cloudQrDataUrl && cloudQrUrl && (
                <div className="flex flex-wrap items-start gap-4 border-t border-surface-border px-4 py-4 sm:px-5">
                  <img
                    src={cloudQrDataUrl}
                    alt={`QR de conexión nube ${cloudQrUrl}`}
                    className="rounded-xl border border-surface-border bg-white p-2 shadow-sm"
                  />
                  <div className="min-w-0 space-y-1.5">
                    <div className="flex items-center gap-2 text-sm font-semibold text-slate-900">
                      <Smartphone className="h-4 w-4 text-brand-600" />
                      QR para celulares (nube)
                    </div>
                    <p className="text-xs leading-relaxed text-slate-500">
                      En la APK, login → Nube → “Escanear QR del PC” (o pegá la URL). El código es
                      la URL guardada ahora; si cambia Railway, se actualiza solo.
                    </p>
                    <p className="inline-flex max-w-full break-all rounded-md bg-brand-50 px-2 py-1 font-mono text-xs text-brand-800 ring-1 ring-brand-100">
                      {cloudQrUrl}
                    </p>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="rounded-lg"
                      onClick={() => void copiarUrl(cloudQrUrl)}
                    >
                      {copiedUrl === cloudQrUrl ? (
                        <Check className="h-4 w-4 text-emerald-600" />
                      ) : (
                        <Copy className="h-4 w-4" />
                      )}
                      Copiar URL
                    </Button>
                  </div>
                </div>
              )}
            </div>
          )}

          {connectionMode === 'local' && !hasNetworkConfig && (
            <div className="rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800 ring-1 ring-amber-100">
              En el celular, configurá la IP del PC en el login. La red local avanzada (servidor /
              cliente) está en la app de escritorio.
            </div>
          )}

          {connectionMode === 'local' && hasNetworkConfig && (
            <>
              <div className="grid gap-3 sm:grid-cols-2">
                <ModeOption
                  active={mode === 'server'}
                  icon={Server}
                  title="Esta PC es el servidor"
                  description="Base de datos local. Otras PCs y celulares se conectan acá."
                  onClick={() => setMode('server')}
                />
                <ModeOption
                  active={mode === 'client'}
                  icon={Wifi}
                  title="Esta PC es cliente"
                  description="Sin base local. Se conecta al servidor por IP de red."
                  onClick={() => {
                    setMode('client')
                    if (remoteHost.trim() === '127.0.0.1' || !remoteHost.trim()) setRemoteHost('')
                    setConnectionTest('idle')
                  }}
                />
              </div>

              <div className="space-y-4">
                {mode === 'client' && (
                  <div className="space-y-1 sm:grid sm:grid-cols-[minmax(0,1fr)_7rem] sm:gap-4 sm:space-y-0">
                    <div className="space-y-1">
                      <Input
                        label="IP del servidor"
                        value={remoteHost}
                        onChange={(e) => {
                          setRemoteHost(e.target.value)
                          setConnectionTest('idle')
                        }}
                        onPaste={(e) => {
                          const pasted = e.clipboardData.getData('text')
                          const parsed = parseServerConnection(pasted)
                          if (!parsed) return
                          e.preventDefault()
                          setRemoteHost(parsed.host)
                          if (parsed.port) setPort(parsed.port)
                          setConnectionTest('idle')
                        }}
                        placeholder="192.168.1.50"
                        className="rounded-xl shadow-sm"
                      />
                      <p className="text-xs leading-relaxed text-slate-500">
                        Solo la IP (ej. 192.168.1.50). También podés pegar la URL completa del
                        servidor.
                        <strong className="text-amber-700"> No uses 127.0.0.1</strong> — es esta PC,
                        no el servidor.
                      </p>
                    </div>
                    <Input
                      label="Puerto"
                      value={port}
                      onChange={(e) => {
                        setPort(e.target.value.replace(/\D/g, ''))
                        setConnectionTest('idle')
                      }}
                      inputMode="numeric"
                      className="rounded-xl shadow-sm"
                    />
                  </div>
                )}
                {mode === 'server' && (
                  <Input
                    label="Puerto de red"
                    value={port}
                    onChange={(e) => setPort(e.target.value.replace(/\D/g, ''))}
                    inputMode="numeric"
                    className="max-w-[8rem] rounded-xl shadow-sm"
                  />
                )}
              </div>

              {mode === 'server' && (
                <div className="space-y-4 rounded-xl border border-surface-border bg-slate-50/80 p-4 sm:p-5">
                  <div className="flex flex-wrap items-center gap-2">
                    <StatusPill tone={networkInfo?.serverRunning ? 'success' : 'warning'}>
                      {networkInfo?.serverRunning ? 'Servidor activo' : 'Servidor inactivo'}
                    </StatusPill>
                    <span className="text-xs text-slate-500">
                      Escuchando en la red local (puerto {port || '3847'})
                    </span>
                  </div>

                  {networkInfo?.connectionUrls.length ? (
                    <div className="space-y-2">
                      <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                        URLs para abrir en celular o navegador
                      </p>
                      <ul className="space-y-2">
                        {networkInfo.connectionUrls.map((url) => (
                          <li
                            key={url}
                            className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-surface-border bg-white px-3 py-2.5 shadow-sm"
                          >
                            <code className="min-w-0 break-all font-mono text-sm text-slate-800">
                              {url}
                            </code>
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              className="shrink-0 rounded-lg"
                              onClick={() => void copiarUrl(url)}
                            >
                              {copiedUrl === url ? (
                                <Check className="h-4 w-4 text-emerald-600" />
                              ) : (
                                <Copy className="h-4 w-4" />
                              )}
                              Copiar
                            </Button>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ) : (
                    <p className="rounded-xl bg-amber-50 px-3 py-2 text-sm text-amber-800 ring-1 ring-amber-100">
                      No se detectó una IP de red local. Verificá que la PC esté conectada al
                      WiFi/LAN.
                    </p>
                  )}

                  {qrDataUrl && primaryConnectionUrl && (
                    <div className="flex flex-wrap items-start gap-4 border-t border-surface-border pt-4">
                      <img
                        src={qrDataUrl}
                        alt={`QR de conexión ${primaryConnectionUrl}`}
                        className="rounded-xl border border-surface-border bg-white p-2 shadow-sm"
                      />
                      <div className="min-w-0 space-y-1.5">
                        <div className="flex items-center gap-2 text-sm font-semibold text-slate-900">
                          <Smartphone className="h-4 w-4 text-brand-600" />
                          Abrir desde celular o navegador
                        </div>
                        <p className="text-xs leading-relaxed text-slate-500">
                          Escaneá este QR desde la APK en el login (botón “Escanear QR del PC”), o abrí
                          la URL en el navegador del celular (misma WiFi).
                        </p>
                        <p className="inline-flex rounded-md bg-brand-50 px-2 py-1 font-mono text-xs text-brand-800 ring-1 ring-brand-100">
                          {primaryConnectionUrl}
                        </p>
                      </div>
                    </div>
                  )}

                  <p className="text-xs leading-relaxed text-slate-500">
                    Si otras PCs o celulares no conectan, permití ControlStock en el firewall de
                    Windows para el puerto {port || '3847'}.
                  </p>
                </div>
              )}

              {mode === 'client' && (
                <div className="space-y-3 rounded-xl border border-surface-border bg-slate-50/80 p-4 sm:p-5">
                  <p className="text-sm text-slate-600">
                    Ingresá la IP del PC servidor (la ves en Configuración del servidor). Puerto por
                    defecto: <strong>3847</strong>.
                  </p>
                  <Button
                    type="button"
                    variant="secondary"
                    size="sm"
                    className="rounded-xl"
                    disabled={connectionTest === 'testing'}
                    onClick={() => void probarConexion()}
                  >
                    {connectionTest === 'testing' ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Probando…
                      </>
                    ) : (
                      'Probar conexión'
                    )}
                  </Button>
                  {connectionTest === 'ok' && (
                    <p className="rounded-xl bg-emerald-50 px-3 py-2.5 text-sm text-emerald-800 ring-1 ring-emerald-100">
                      {connectionMessage}
                    </p>
                  )}
                  {connectionTest === 'fail' && (
                    <p className="rounded-xl bg-red-50 px-3 py-2.5 text-sm text-red-800 ring-1 ring-red-100">
                      {connectionMessage}
                    </p>
                  )}
                </div>
              )}

              <div className="flex flex-wrap gap-2 border-t border-surface-border pt-5">
                <Button
                  type="button"
                  className="rounded-xl"
                  disabled={savingNetwork}
                  onClick={() => void guardarRed()}
                >
                  {savingNetwork ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Guardando…
                    </>
                  ) : (
                    'Guardar y reiniciar'
                  )}
                </Button>
                <Button
                  type="button"
                  variant="secondary"
                  className="rounded-xl"
                  onClick={() => void loadNetworkInfo()}
                >
                  Descartar cambios
                </Button>
              </div>
              <p className="text-xs text-slate-400">
                Los cambios de modo o puerto requieren reiniciar la aplicación.
              </p>
            </>
          )}
        </CardBody>
      </Card>

      {user?.es_admin && (
      <Card className="overflow-hidden shadow-panel">
        <button
          type="button"
          className="flex w-full items-start gap-3 border-b border-brand-100 bg-gradient-to-r from-brand-50/80 via-white to-white px-5 py-4 text-left transition hover:from-brand-50 sm:px-6"
          onClick={() => setMigPanelOpen((open) => !open)}
          aria-expanded={migPanelOpen}
        >
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-600 text-white shadow-sm">
            <Database className="h-5 w-5" />
          </div>
          <div className="min-w-0 flex-1">
            <h2 className="font-semibold text-slate-900">Migrar datos a la nube</h2>
            <p className="mt-0.5 text-sm text-slate-500">
              {migPanelOpen
                ? 'Copia la base SQLite de esta PC hacia Postgres en Railway'
                : 'Oculto · tocá para abrir (solo cuando haga falta)'}
            </p>
          </div>
          <ChevronDown
            className={cn(
              'mt-2 h-5 w-5 shrink-0 text-slate-400 transition-transform',
              migPanelOpen && 'rotate-180'
            )}
          />
        </button>
        {migPanelOpen && (
          <CardBody className="space-y-4 p-5 sm:p-6">
            {connectionMode !== 'cloud' ? (
              <p className="rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600 ring-1 ring-slate-200">
                Activá primero <strong>Nube (Railway)</strong> arriba, guardá la URL y entrá con un
                admin de la nube. Después volvé acá a migrar.
              </p>
            ) : !api?.exportLocalDatabase ? (
              <p className="rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800 ring-1 ring-amber-100">
                La migración se hace desde la app de escritorio (lee el SQLite local).
              </p>
            ) : (
              <>
                <p className="text-sm leading-relaxed text-slate-600">
                  Esto <strong>reemplaza</strong> todos los datos actuales de la nube con los de esta
                  PC. Las imágenes de productos no se suben (quedan en el disco local por ahora).
                  Después cerrá sesión y entrá con un usuario de la base migrada.
                </p>
                <p className="text-xs text-slate-500">
                  Destino: <code className="font-mono text-slate-700">{getApiUrl()}</code>
                </p>
                <Input
                  label="Escribí MIGRAR para confirmar"
                  value={migConfirmacion}
                  onChange={(e) => setMigConfirmacion(e.target.value)}
                  placeholder="MIGRAR"
                  className="max-w-xs rounded-xl shadow-sm"
                  autoComplete="off"
                />
                <Button
                  type="button"
                  className="rounded-xl"
                  disabled={migrating || migConfirmacion.trim() !== 'MIGRAR'}
                  onClick={() => void migrarLocalANube()}
                >
                  {migrating ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Migrando…
                    </>
                  ) : (
                    <>
                      <Database className="h-4 w-4" />
                      Migrar SQLite local → nube
                    </>
                  )}
                </Button>
                {migOk && (
                  <p className="rounded-xl bg-emerald-50 px-3 py-2.5 text-sm text-emerald-800 ring-1 ring-emerald-100">
                    {migOk}
                  </p>
                )}
                {migError && (
                  <p className="rounded-xl bg-red-50 px-3 py-2.5 text-sm text-red-800 ring-1 ring-red-100">
                    {migError}
                  </p>
                )}
                {migCounts && (
                  <details className="rounded-xl border border-surface-border bg-slate-50/80 px-3 py-2 text-xs text-slate-600">
                    <summary className="cursor-pointer font-semibold">Ver conteo de filas</summary>
                    <ul className="mt-2 max-h-40 space-y-0.5 overflow-auto font-mono">
                      {Object.entries(migCounts)
                        .filter(([, n]) => n > 0)
                        .map(([table, n]) => (
                          <li key={table}>
                            {table}: {n}
                          </li>
                        ))}
                    </ul>
                  </details>
                )}
              </>
            )}
          </CardBody>
        )}
      </Card>
      )}

      <Card className="overflow-hidden shadow-panel">
        <div className="border-b border-brand-100 bg-gradient-to-r from-brand-50/80 via-white to-white px-5 py-4 sm:px-6">
          <div className="flex items-start gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-600 text-white shadow-sm">
              <ClipboardCheck className="h-5 w-5" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-900">Verificación de documentos</h2>
              <p className="mt-0.5 text-sm text-slate-500">
                Doble control digital o ingreso directo (control en hoja)
              </p>
            </div>
          </div>
        </div>

        <CardBody className="space-y-4 p-5 sm:p-6">
          {loadingOpCfg ? (
            <p className="flex items-center gap-2 text-sm text-slate-500">
              <Loader2 className="h-4 w-4 animate-spin" />
              Cargando…
            </p>
          ) : (
            <>
              <label className="flex cursor-pointer items-start gap-3 rounded-xl border border-surface-border bg-slate-50/80 p-4">
                <input
                  type="checkbox"
                  className="mt-1 h-4 w-4 rounded border-slate-300 text-brand-600 focus:ring-brand-500"
                  checked={dobleVerificacionRetornos}
                  disabled={savingRetornosCfg}
                  onChange={(e) => void guardarRetornosCfg(e.target.checked)}
                />
                <span className="min-w-0">
                  <span className="flex items-center gap-2 text-sm font-semibold text-slate-900">
                    Retornos — doble verificación
                  </span>
                  <span className="mt-1 block text-sm leading-relaxed text-slate-500">
                    {dobleVerificacionRetornos
                      ? 'Un usuario carga y otro distinto confirma antes de sumar stock.'
                      : 'Al confirmar el retorno queda verificado y suma stock de inmediato.'}
                  </span>
                </span>
              </label>

              <label className="flex cursor-pointer items-start gap-3 rounded-xl border border-surface-border bg-slate-50/80 p-4">
                <input
                  type="checkbox"
                  className="mt-1 h-4 w-4 rounded border-slate-300 text-brand-600 focus:ring-brand-500"
                  checked={dobleVerificacionMovimientos}
                  disabled={savingMovimientosCfg}
                  onChange={(e) => void guardarMovimientosCfg(e.target.checked)}
                />
                <span className="min-w-0">
                  <span className="flex items-center gap-2 text-sm font-semibold text-slate-900">
                    <ArrowLeftRight className="h-4 w-4 text-slate-500" />
                    Movimientos internos — doble verificación
                  </span>
                  <span className="mt-1 block text-sm leading-relaxed text-slate-500">
                    {dobleVerificacionMovimientos
                      ? 'En la lista abierta hay que tildar cada línea antes de finalizar (mueve stock al confirmar).'
                      : 'Al finalizar la lista mueve stock sin tildar líneas (ingreso directo / control en hoja).'}
                  </span>
                </span>
              </label>

              {(!dobleVerificacionRetornos || !dobleVerificacionMovimientos) && (
                <div className="rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-900 ring-1 ring-amber-100">
                  Los documentos en modo ingreso directo quedan marcados para auditoría.
                </div>
              )}

              {opCfgSaved && (
                <p className="flex items-center gap-1.5 text-sm text-emerald-700">
                  <Check className="h-4 w-4" />
                  Configuración de {opCfgSaved === 'retornos' ? 'retornos' : 'movimientos'} guardada
                </p>
              )}
            </>
          )}

          {opCfgError && (
            <div className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800 ring-1 ring-red-100">
              {opCfgError}
            </div>
          )}
        </CardBody>
      </Card>

      <Card className="overflow-hidden shadow-panel">
        <div className="border-b border-violet-100 bg-gradient-to-r from-violet-50/80 via-white to-white px-5 py-4 sm:px-6">
          <div className="flex items-start gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-600 text-white shadow-sm">
              <RefreshCw className="h-5 w-5" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-900">Actualizar sistema</h2>
              <p className="mt-0.5 text-sm text-slate-500">
                Comprobá e instalá nuevas versiones de ControlStock
              </p>
            </div>
          </div>
        </div>

        <CardBody className="space-y-4 p-5 sm:p-6">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm text-slate-600">Versión instalada:</span>
            <StatusPill tone="brand">{appInfo?.version ?? '…'}</StatusPill>
            {isElectron && (
              <StatusPill tone={isPackaged ? 'success' : 'warning'}>
                {isPackaged ? 'Instalada en PC' : 'Modo desarrollo'}
              </StatusPill>
            )}
          </div>

          {!isElectron && (
            <div className="rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800 ring-1 ring-amber-100">
              Está usando la versión web. Las actualizaciones automáticas están disponibles solo en
              la aplicación de escritorio instalada.
            </div>
          )}

          {phase === 'dev-mode' && (
            <div className="rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600 ring-1 ring-surface-border">
              En modo desarrollo no se buscan actualizaciones. Genere e instale el instalador (.exe)
              para probar las actualizaciones automáticas.
            </div>
          )}

          {phase === 'checking' && (
            <div className="flex items-center gap-2 text-sm text-slate-600">
              <Loader2 className="h-4 w-4 animate-spin text-brand-600" />
              Buscando actualizaciones…
            </div>
          )}

          {phase === 'not-available' && (
            <div className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800 ring-1 ring-emerald-100">
              Ya tiene la última versión ({availableVersion || appInfo?.version}).
            </div>
          )}

          {phase === 'available' && (
            <div className="space-y-3 rounded-xl border border-brand-200 bg-gradient-to-br from-brand-50/90 to-white p-4 ring-1 ring-brand-100">
              <p className="text-sm font-semibold text-brand-900">
                Hay una nueva versión disponible: {availableVersion}
              </p>
              {releaseNotes ? (
                <div className="max-h-40 space-y-1 overflow-y-auto rounded-lg bg-white/80 px-3 py-2 text-xs leading-relaxed text-brand-800 ring-1 ring-brand-100">
                  {releaseNotes.split('\n').map((line, index) => (
                    <p key={`${index}-${line}`}>{line}</p>
                  ))}
                </div>
              ) : (
                <p className="text-xs leading-relaxed text-brand-700/90">
                  Descargá e instalá la actualización para obtener las últimas mejoras del sistema.
                </p>
              )}
              <Button size="sm" className="rounded-xl" onClick={() => void descargarActualizacion()}>
                <Download className="h-4 w-4" />
                Descargar actualización
              </Button>
            </div>
          )}

          {phase === 'downloading' && (
            <div className="space-y-3 rounded-xl border-2 border-brand-300 bg-gradient-to-br from-brand-50 to-white p-4 shadow-sm ring-1 ring-brand-100">
              <div className="flex flex-wrap items-start justify-between gap-2">
                <div>
                  <p className="flex items-center gap-2 text-sm font-semibold text-brand-900">
                    <Loader2 className="h-4 w-4 animate-spin text-brand-600" />
                    Descargando actualización…
                  </p>
                  <p className="mt-1 text-xs text-brand-700/80">
                    No cierres la aplicación. Podés seguir trabajando; el progreso también se ve
                    arriba.
                  </p>
                </div>
                <span className="shrink-0 rounded-lg bg-brand-600 px-2.5 py-1 text-sm font-bold tabular-nums text-white">
                  {downloadPercent}%
                </span>
              </div>
              <div className="h-3.5 overflow-hidden rounded-full bg-brand-100 ring-1 ring-brand-200/80">
                <div
                  className={
                    downloadPercent <= 0
                      ? 'h-full w-1/3 animate-pulse rounded-full bg-brand-600'
                      : 'h-full rounded-full bg-brand-600 transition-all duration-300'
                  }
                  style={downloadPercent > 0 ? { width: `${downloadPercent}%` } : undefined}
                />
              </div>
              {downloadDetail && (
                <p className="text-center text-xs tabular-nums text-slate-600">{downloadDetail}</p>
              )}
            </div>
          )}

          {phase === 'downloaded' && (
            <div className="space-y-3 rounded-xl border border-emerald-200 bg-gradient-to-br from-emerald-50/90 to-white p-4 ring-1 ring-emerald-100">
              <p className="text-sm font-semibold text-emerald-900">
                Versión {availableVersion} descargada. Al instalar se abre el Setup de Windows con
                su barra de progreso (como instalar a mano).
              </p>
              <Button size="sm" className="rounded-xl" onClick={() => void instalarActualizacion()}>
                Instalar y reiniciar
              </Button>
            </div>
          )}

          {phase === 'installing' && (
            <div className="space-y-3 rounded-xl border-2 border-brand-300 bg-gradient-to-br from-brand-50 to-white p-4 shadow-sm">
              <p className="flex items-center gap-2 text-sm font-semibold text-brand-900">
                <Loader2 className="h-4 w-4 animate-spin text-brand-600" />
                Abriendo el instalador de Windows…
              </p>
              <p className="text-xs leading-relaxed text-brand-800/90">
                Buscá la ventana del instalador de ControlStock: ahí está la barra de progreso. Si
                Windows pide permiso, aceptá y seguí los pasos del Setup.
              </p>
              <div className="h-3.5 overflow-hidden rounded-full bg-brand-100">
                <div className="h-full w-1/3 animate-pulse rounded-full bg-brand-600" />
              </div>
            </div>
          )}

          {phase === 'error' && errorMessage && (
            <div className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800 ring-1 ring-red-100">
              {errorMessage}
            </div>
          )}

          <div className="flex flex-wrap gap-2 pt-1">
            <Button
              variant="secondary"
              size="sm"
              className="rounded-xl"
              disabled={
                phase === 'checking' || phase === 'downloading' || phase === 'installing'
              }
              onClick={() => void buscarActualizaciones()}
            >
              <RefreshCw className={cn('h-4 w-4', phase === 'checking' && 'animate-spin')} />
              Buscar actualizaciones
            </Button>
          </div>

          {isPackaged && (
            <p className="text-xs leading-relaxed text-slate-400">
              Las actualizaciones se descargan desde{' '}
              <a
                href="https://github.com/JRNCarrizo/bodegaStock/releases"
                className="text-brand-600 hover:underline"
                onClick={(e) => {
                  e.preventDefault()
                  window.open('https://github.com/JRNCarrizo/bodegaStock/releases', '_blank')
                }}
              >
                GitHub Releases
              </a>
              . Si esta versión fue instalada antes de v0.2.2, puede ser necesario actualizar
              manualmente una vez.
            </p>
          )}
        </CardBody>
      </Card>

      {user?.es_admin && (
        <div className="border-t border-slate-100 pt-6">
          <button
            type="button"
            className="text-xs text-slate-400 underline-offset-2 hover:text-slate-600 hover:underline"
            onClick={() => {
              setShowResetStock((v) => !v)
              setResetStockError('')
              setResetConfirmacion('')
              setWipeDbError('')
              setWipeConfirmacion('')
            }}
          >
            Herramientas de prueba
          </button>

          {showResetStock && (
            <div className="mt-3 max-w-lg space-y-4">
              <div className="space-y-3 rounded-xl border border-slate-200 bg-slate-50/60 px-4 py-4">
                <div>
                  <p className="text-sm font-medium text-slate-800">Poner stock en cero</p>
                  <p className="mt-1 text-xs leading-relaxed text-slate-500">
                    Borra todas las líneas de stock y deja los totales en 0. No elimina productos,
                    sectores ni usuarios. Útil después de pruebas con stock ficticio. No se puede
                    usar con un inventario en curso.
                  </p>
                </div>
                <div className="flex flex-col gap-2 sm:flex-row sm:items-end">
                  <div className="min-w-0 flex-1">
                    <label className="mb-1 block text-xs text-slate-500">
                      Escribí <span className="font-semibold text-slate-700">CERO</span> para
                      confirmar
                    </label>
                    <Input
                      value={resetConfirmacion}
                      onChange={(e) => setResetConfirmacion(e.target.value)}
                      placeholder="CERO"
                      className="rounded-xl"
                      autoComplete="off"
                      disabled={resettingStock}
                    />
                  </div>
                  <Button
                    variant="secondary"
                    size="sm"
                    className="rounded-xl text-red-700 ring-1 ring-red-200 hover:bg-red-50"
                    disabled={resettingStock || resetConfirmacion.trim().toUpperCase() !== 'CERO'}
                    onClick={() => void resetearStockACero()}
                  >
                    {resettingStock ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Procesando…
                      </>
                    ) : (
                      'Poner stock en cero'
                    )}
                  </Button>
                </div>
                {resetStockError && (
                  <div className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-800 ring-1 ring-red-100">
                    {resetStockError}
                  </div>
                )}
              </div>

              <div className="space-y-3 rounded-xl border border-red-100 bg-red-50/40 px-4 py-4">
                <div>
                  <p className="text-sm font-medium text-slate-800">Eliminar base de datos</p>
                  <p className="mt-1 text-xs leading-relaxed text-slate-500">
                    Borra productos, sectores, stock, usuarios e historial. Se conservan modo/red.
                    Al terminar la app se reinicia con usuario{' '}
                    <span className="font-medium text-slate-700">admin / admin123</span>. Solo en
                    este PC (modo servidor).
                  </p>
                </div>
                <div className="flex flex-col gap-2 sm:flex-row sm:items-end">
                  <div className="min-w-0 flex-1">
                    <label className="mb-1 block text-xs text-slate-500">
                      Escribí <span className="font-semibold text-slate-700">BORRAR</span> para
                      confirmar
                    </label>
                    <Input
                      value={wipeConfirmacion}
                      onChange={(e) => setWipeConfirmacion(e.target.value)}
                      placeholder="BORRAR"
                      className="rounded-xl"
                      autoComplete="off"
                      disabled={wipingDb}
                    />
                  </div>
                  <Button
                    variant="secondary"
                    size="sm"
                    className="rounded-xl bg-red-600 text-white hover:bg-red-700"
                    disabled={wipingDb || wipeConfirmacion.trim().toUpperCase() !== 'BORRAR'}
                    onClick={() => void borrarBaseYReiniciar()}
                  >
                    {wipingDb ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Reiniciando…
                      </>
                    ) : (
                      'Borrar y reiniciar'
                    )}
                  </Button>
                </div>
                {wipeDbError && (
                  <div className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-800 ring-1 ring-red-100">
                    {wipeDbError}
                  </div>
                )}
              </div>
            </div>
          )}

          {resetStockOk && (
            <p className="mt-3 flex items-start gap-1.5 text-sm text-emerald-700">
              <Check className="mt-0.5 h-4 w-4 shrink-0" />
              {resetStockOk}
            </p>
          )}
        </div>
      )}

      <AppCopyrightFooter />
    </div>
  )
}
