import { useCallback, useEffect, useMemo, useState } from 'react'
import QRCode from 'qrcode'
import {
  Check,
  Copy,
  Download,
  Loader2,
  RefreshCw,
  Server,
  Smartphone,
  Wifi
} from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Card, CardBody } from '@/components/ui/Card'
import { cn } from '@/lib/utils'
import { isAutoGeneratedChangelogOnly, plainTextReleaseNotes } from '@/lib/releaseNotes'
import type {
  AppInfo,
  NetworkConfig,
  NetworkRuntimeInfo,
  UpdateStatusPayload
} from '@/vite-env'

type UpdatePhase =
  | 'idle'
  | 'checking'
  | 'available'
  | 'not-available'
  | 'downloading'
  | 'downloaded'
  | 'error'
  | 'dev-mode'

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function displayRemoteHost(host: string): string {
  const trimmed = host.trim()
  return trimmed === '127.0.0.1' ? '' : trimmed
}

function parseServerConnection(raw: string): { host: string; port?: string } | null {
  const value = raw.trim()
  if (!value) return null

  try {
    const url = value.includes('://') ? new URL(value) : new URL(`http://${value}`)
    const host = url.hostname
    const port = url.port || undefined
    if (!host) return null
    return { host, port }
  } catch {
    const match = value.match(/^([\d.]+)(?::(\d+))?$/)
    if (!match) return null
    return { host: match[1], port: match[2] }
  }
}

function StatusPill({
  tone,
  children
}: {
  tone: 'success' | 'warning' | 'neutral' | 'brand'
  children: React.ReactNode
}) {
  const styles = {
    success: 'bg-emerald-50 text-emerald-800 ring-emerald-100',
    warning: 'bg-amber-50 text-amber-800 ring-amber-100',
    neutral: 'bg-slate-100 text-slate-700 ring-surface-border',
    brand: 'bg-brand-50 text-brand-800 ring-brand-100'
  }
  return (
    <span
      className={cn(
        'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ring-1',
        styles[tone]
      )}
    >
      {children}
    </span>
  )
}

function ModeOption({
  active,
  icon: Icon,
  title,
  description,
  onClick
}: {
  active: boolean
  icon: typeof Server
  title: string
  description: string
  onClick: () => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'rounded-xl border px-4 py-3.5 text-left transition-all',
        active
          ? 'border-brand-500 bg-brand-50 shadow-sm ring-2 ring-brand-500/20'
          : 'border-surface-border bg-white hover:border-slate-300 hover:bg-slate-50/80'
      )}
    >
      <div className="flex items-center gap-2.5">
        <div
          className={cn(
            'flex h-9 w-9 shrink-0 items-center justify-center rounded-lg',
            active ? 'bg-brand-600 text-white' : 'bg-slate-100 text-slate-600'
          )}
        >
          <Icon className="h-4 w-4" />
        </div>
        <span className="text-sm font-semibold text-slate-900">{title}</span>
      </div>
      <p className="mt-2 pl-[2.875rem] text-xs leading-relaxed text-slate-500">{description}</p>
    </button>
  )
}

export function ConfiguracionPage() {
  const api = window.bodegaStock
  const [appInfo, setAppInfo] = useState<AppInfo | null>(null)
  const [networkInfo, setNetworkInfo] = useState<NetworkRuntimeInfo | null>(null)
  const [mode, setMode] = useState<NetworkConfig['mode']>('server')
  const [remoteHost, setRemoteHost] = useState('')
  const [port, setPort] = useState('3847')
  const [connectionTest, setConnectionTest] = useState<'idle' | 'testing' | 'ok' | 'fail'>('idle')
  const [connectionMessage, setConnectionMessage] = useState('')
  const [savingNetwork, setSavingNetwork] = useState(false)
  const [copiedUrl, setCopiedUrl] = useState('')
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null)
  const [phase, setPhase] = useState<UpdatePhase>('idle')
  const [availableVersion, setAvailableVersion] = useState('')
  const [releaseNotes, setReleaseNotes] = useState('')
  const [downloadPercent, setDownloadPercent] = useState(0)
  const [downloadDetail, setDownloadDetail] = useState('')
  const [errorMessage, setErrorMessage] = useState('')

  const primaryConnectionUrl = useMemo(
    () => networkInfo?.connectionUrls[0] ?? '',
    [networkInfo?.connectionUrls]
  )

  const loadNetworkInfo = useCallback(async () => {
    if (!api?.getNetworkInfo) return
    const info = await api.getNetworkInfo()
    setNetworkInfo(info)
    setMode(info.config.mode)
    setRemoteHost(displayRemoteHost(info.config.remoteHost))
    setPort(String(info.config.port))
  }, [api])

  useEffect(() => {
    void loadNetworkInfo()
  }, [loadNetworkInfo])

  useEffect(() => {
    if (!primaryConnectionUrl || mode !== 'server') {
      setQrDataUrl(null)
      return
    }

    void QRCode.toDataURL(primaryConnectionUrl, {
      margin: 1,
      width: 180,
      color: { dark: '#0f172a', light: '#ffffff' }
    }).then(setQrDataUrl)
  }, [primaryConnectionUrl, mode])

  const handleStatus = useCallback((status: UpdateStatusPayload) => {
    switch (status.type) {
      case 'checking':
        setPhase('checking')
        setErrorMessage('')
        break
      case 'available':
        setPhase('available')
        setAvailableVersion(status.version)
        {
          const notes = plainTextReleaseNotes(status.releaseNotes)
          setReleaseNotes(notes && !isAutoGeneratedChangelogOnly(notes) ? notes : '')
        }
        break
      case 'not-available':
        setPhase('not-available')
        setAvailableVersion(status.version)
        break
      case 'download-progress':
        setPhase('downloading')
        setDownloadPercent(Math.round(status.percent))
        setDownloadDetail(`${formatBytes(status.transferred)} / ${formatBytes(status.total)}`)
        break
      case 'downloaded':
        setPhase('downloaded')
        setAvailableVersion(status.version)
        break
      case 'error':
        setPhase('error')
        setErrorMessage(status.message)
        break
    }
  }, [])

  useEffect(() => {
    if (!api?.getAppInfo) return
    void api.getAppInfo().then(setAppInfo)
  }, [api])

  useEffect(() => {
    if (!api?.onUpdateStatus) return
    return api.onUpdateStatus(handleStatus)
  }, [api, handleStatus])

  async function buscarActualizaciones() {
    if (!api?.checkForUpdates) {
      setPhase('dev-mode')
      return
    }

    setPhase('checking')
    setErrorMessage('')

    const result = await api.checkForUpdates()
    if (result.reason === 'dev') {
      setPhase('dev-mode')
      return
    }
    if (!result.ok) {
      setPhase('error')
      setErrorMessage(
        result.message ??
          'No se pudo comprobar actualizaciones. Verifique que la app esté instalada y que exista un servidor de releases configurado.'
      )
    }
  }

  async function descargarActualizacion() {
    if (!api?.downloadUpdate) return
    setPhase('downloading')
    setDownloadPercent(0)
    const result = await api.downloadUpdate()
    if (!result.ok) {
      setPhase('error')
      setErrorMessage(result.message ?? 'Error al descargar la actualización')
    }
  }

  async function instalarActualizacion() {
    if (!api?.installUpdate) return
    await api.installUpdate()
  }

  async function probarConexion() {
    if (!api?.testNetworkConnection) return

    setConnectionTest('testing')
    setConnectionMessage('')

    const result = await api.testNetworkConnection(remoteHost.trim(), Number(port) || 3847)
    if (result.ok) {
      setConnectionTest('ok')
      setConnectionMessage(
        result.version
          ? `Conectado a ${result.app ?? 'ControlStock'} v${result.version}`
          : 'Conexión exitosa con el servidor'
      )
      return
    }

    setConnectionTest('fail')
    setConnectionMessage(result.message ?? 'No se pudo conectar')
  }

  async function guardarRed() {
    if (!api?.applyNetworkConfig) return

    const host = remoteHost.trim()
    if (mode === 'client' && !host) {
      setConnectionTest('fail')
      setConnectionMessage(
        'Ingresá la IP del servidor (no uses 127.0.0.1 salvo que el servidor sea esta misma PC).'
      )
      return
    }

    setSavingNetwork(true)
    try {
      await api.applyNetworkConfig({
        mode,
        remoteHost: host || '127.0.0.1',
        port: Number(port) || 3847
      })
    } finally {
      setSavingNetwork(false)
    }
  }

  async function copiarUrl(url: string) {
    await navigator.clipboard.writeText(url)
    setCopiedUrl(url)
    setTimeout(() => setCopiedUrl(''), 2000)
  }

  const isElectron = Boolean(api?.getAppInfo)
  const isPackaged = appInfo?.isPackaged ?? false
  const hasNetworkConfig = Boolean(api?.applyNetworkConfig)

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <section>
        <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Sistema</p>
        <h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">
          Configuración
        </h1>
        <p className="mt-2 max-w-xl text-sm leading-relaxed text-slate-500">
          Red local para clientes y celulares, actualizaciones automáticas e información de la
          aplicación.
        </p>
      </section>

      <Card className="overflow-hidden shadow-panel">
        <div className="border-b border-brand-100 bg-gradient-to-r from-brand-50/80 via-white to-white px-5 py-4 sm:px-6">
          <div className="flex items-start gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-600 text-white shadow-sm">
              <Wifi className="h-5 w-5" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-900">Red y conexión</h2>
              <p className="mt-0.5 text-sm text-slate-500">
                Servidor en una PC; otras PCs y celulares se conectan por WiFi/LAN
              </p>
            </div>
          </div>
        </div>

        <CardBody className="space-y-5 p-5 sm:p-6">
          {!hasNetworkConfig ? (
            <div className="rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800 ring-1 ring-amber-100">
              La configuración de red está disponible en la aplicación de escritorio instalada.
            </div>
          ) : (
            <>
              <div className="grid gap-3 sm:grid-cols-2">
                <ModeOption
                  active={mode === 'server'}
                  icon={Server}
                  title="Esta PC es el servidor"
                  description="Base de datos local. Otras PCs y celulares se conectan acá."
                  onClick={() => setMode('server')}
                />
                <ModeOption
                  active={mode === 'client'}
                  icon={Wifi}
                  title="Esta PC es cliente"
                  description="Sin base local. Se conecta al servidor por IP de red."
                  onClick={() => {
                    setMode('client')
                    if (remoteHost.trim() === '127.0.0.1' || !remoteHost.trim()) setRemoteHost('')
                    setConnectionTest('idle')
                  }}
                />
              </div>

              <div className="space-y-4">
                {mode === 'client' && (
                  <div className="space-y-1 sm:grid sm:grid-cols-[minmax(0,1fr)_7rem] sm:gap-4 sm:space-y-0">
                    <div className="space-y-1">
                      <Input
                        label="IP del servidor"
                        value={remoteHost}
                        onChange={(e) => {
                          setRemoteHost(e.target.value)
                          setConnectionTest('idle')
                        }}
                        onPaste={(e) => {
                          const pasted = e.clipboardData.getData('text')
                          const parsed = parseServerConnection(pasted)
                          if (!parsed) return
                          e.preventDefault()
                          setRemoteHost(parsed.host)
                          if (parsed.port) setPort(parsed.port)
                          setConnectionTest('idle')
                        }}
                        placeholder="192.168.1.50"
                        className="rounded-xl shadow-sm"
                      />
                      <p className="text-xs leading-relaxed text-slate-500">
                        Solo la IP (ej. 192.168.1.50). También podés pegar la URL completa del
                        servidor.
                        <strong className="text-amber-700"> No uses 127.0.0.1</strong> — es esta PC,
                        no el servidor.
                      </p>
                    </div>
                    <Input
                      label="Puerto"
                      value={port}
                      onChange={(e) => {
                        setPort(e.target.value.replace(/\D/g, ''))
                        setConnectionTest('idle')
                      }}
                      inputMode="numeric"
                      className="rounded-xl shadow-sm"
                    />
                  </div>
                )}
                {mode === 'server' && (
                  <Input
                    label="Puerto de red"
                    value={port}
                    onChange={(e) => setPort(e.target.value.replace(/\D/g, ''))}
                    inputMode="numeric"
                    className="max-w-[8rem] rounded-xl shadow-sm"
                  />
                )}
              </div>

              {mode === 'server' && (
                <div className="space-y-4 rounded-xl border border-surface-border bg-slate-50/80 p-4 sm:p-5">
                  <div className="flex flex-wrap items-center gap-2">
                    <StatusPill tone={networkInfo?.serverRunning ? 'success' : 'warning'}>
                      {networkInfo?.serverRunning ? 'Servidor activo' : 'Servidor inactivo'}
                    </StatusPill>
                    <span className="text-xs text-slate-500">
                      Escuchando en la red local (puerto {port || '3847'})
                    </span>
                  </div>

                  {networkInfo?.connectionUrls.length ? (
                    <div className="space-y-2">
                      <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                        URLs para abrir en celular o navegador
                      </p>
                      <ul className="space-y-2">
                        {networkInfo.connectionUrls.map((url) => (
                          <li
                            key={url}
                            className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-surface-border bg-white px-3 py-2.5 shadow-sm"
                          >
                            <code className="min-w-0 break-all font-mono text-sm text-slate-800">
                              {url}
                            </code>
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              className="shrink-0 rounded-lg"
                              onClick={() => void copiarUrl(url)}
                            >
                              {copiedUrl === url ? (
                                <Check className="h-4 w-4 text-emerald-600" />
                              ) : (
                                <Copy className="h-4 w-4" />
                              )}
                              Copiar
                            </Button>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ) : (
                    <p className="rounded-xl bg-amber-50 px-3 py-2 text-sm text-amber-800 ring-1 ring-amber-100">
                      No se detectó una IP de red local. Verificá que la PC esté conectada al
                      WiFi/LAN.
                    </p>
                  )}

                  {qrDataUrl && primaryConnectionUrl && (
                    <div className="flex flex-wrap items-start gap-4 border-t border-surface-border pt-4">
                      <img
                        src={qrDataUrl}
                        alt={`QR de conexión ${primaryConnectionUrl}`}
                        className="rounded-xl border border-surface-border bg-white p-2 shadow-sm"
                      />
                      <div className="min-w-0 space-y-1.5">
                        <div className="flex items-center gap-2 text-sm font-semibold text-slate-900">
                          <Smartphone className="h-4 w-4 text-brand-600" />
                          Abrir desde celular o navegador
                        </div>
                        <p className="text-xs leading-relaxed text-slate-500">
                          Entrá a esta misma URL en el navegador del celular (misma WiFi). Vas a ver el
                          login de ControlStock. La app APK podrá usar el mismo QR más adelante.
                        </p>
                        <p className="inline-flex rounded-md bg-brand-50 px-2 py-1 font-mono text-xs text-brand-800 ring-1 ring-brand-100">
                          {primaryConnectionUrl}
                        </p>
                      </div>
                    </div>
                  )}

                  <p className="text-xs leading-relaxed text-slate-500">
                    Si otras PCs o celulares no conectan, permití ControlStock en el firewall de
                    Windows para el puerto {port || '3847'}.
                  </p>
                </div>
              )}

              {mode === 'client' && (
                <div className="space-y-3 rounded-xl border border-surface-border bg-slate-50/80 p-4 sm:p-5">
                  <p className="text-sm text-slate-600">
                    Ingresá la IP del PC servidor (la ves en Configuración del servidor). Puerto por
                    defecto: <strong>3847</strong>.
                  </p>
                  <Button
                    type="button"
                    variant="secondary"
                    size="sm"
                    className="rounded-xl"
                    disabled={connectionTest === 'testing'}
                    onClick={() => void probarConexion()}
                  >
                    {connectionTest === 'testing' ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Probando…
                      </>
                    ) : (
                      'Probar conexión'
                    )}
                  </Button>
                  {connectionTest === 'ok' && (
                    <p className="rounded-xl bg-emerald-50 px-3 py-2.5 text-sm text-emerald-800 ring-1 ring-emerald-100">
                      {connectionMessage}
                    </p>
                  )}
                  {connectionTest === 'fail' && (
                    <p className="rounded-xl bg-red-50 px-3 py-2.5 text-sm text-red-800 ring-1 ring-red-100">
                      {connectionMessage}
                    </p>
                  )}
                </div>
              )}

              <div className="flex flex-wrap gap-2 border-t border-surface-border pt-5">
                <Button
                  type="button"
                  className="rounded-xl"
                  disabled={savingNetwork}
                  onClick={() => void guardarRed()}
                >
                  {savingNetwork ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Guardando…
                    </>
                  ) : (
                    'Guardar y reiniciar'
                  )}
                </Button>
                <Button
                  type="button"
                  variant="secondary"
                  className="rounded-xl"
                  onClick={() => void loadNetworkInfo()}
                >
                  Descartar cambios
                </Button>
              </div>
              <p className="text-xs text-slate-400">
                Los cambios de modo o puerto requieren reiniciar la aplicación.
              </p>
            </>
          )}
        </CardBody>
      </Card>

      <Card className="overflow-hidden shadow-panel">
        <div className="border-b border-violet-100 bg-gradient-to-r from-violet-50/80 via-white to-white px-5 py-4 sm:px-6">
          <div className="flex items-start gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-600 text-white shadow-sm">
              <RefreshCw className="h-5 w-5" />
            </div>
            <div>
              <h2 className="font-semibold text-slate-900">Actualizar sistema</h2>
              <p className="mt-0.5 text-sm text-slate-500">
                Comprobá e instalá nuevas versiones de ControlStock
              </p>
            </div>
          </div>
        </div>

        <CardBody className="space-y-4 p-5 sm:p-6">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm text-slate-600">Versión instalada:</span>
            <StatusPill tone="brand">{appInfo?.version ?? '…'}</StatusPill>
            {isElectron && (
              <StatusPill tone={isPackaged ? 'success' : 'warning'}>
                {isPackaged ? 'Instalada en PC' : 'Modo desarrollo'}
              </StatusPill>
            )}
          </div>

          {!isElectron && (
            <div className="rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800 ring-1 ring-amber-100">
              Está usando la versión web. Las actualizaciones automáticas están disponibles solo en
              la aplicación de escritorio instalada.
            </div>
          )}

          {phase === 'dev-mode' && (
            <div className="rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600 ring-1 ring-surface-border">
              En modo desarrollo no se buscan actualizaciones. Genere e instale el instalador (.exe)
              para probar las actualizaciones automáticas.
            </div>
          )}

          {phase === 'checking' && (
            <div className="flex items-center gap-2 text-sm text-slate-600">
              <Loader2 className="h-4 w-4 animate-spin text-brand-600" />
              Buscando actualizaciones…
            </div>
          )}

          {phase === 'not-available' && (
            <div className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800 ring-1 ring-emerald-100">
              Ya tiene la última versión ({availableVersion || appInfo?.version}).
            </div>
          )}

          {phase === 'available' && (
            <div className="space-y-3 rounded-xl border border-brand-200 bg-gradient-to-br from-brand-50/90 to-white p-4 ring-1 ring-brand-100">
              <p className="text-sm font-semibold text-brand-900">
                Hay una nueva versión disponible: {availableVersion}
              </p>
              {releaseNotes ? (
                <div className="max-h-40 space-y-1 overflow-y-auto rounded-lg bg-white/80 px-3 py-2 text-xs leading-relaxed text-brand-800 ring-1 ring-brand-100">
                  {releaseNotes.split('\n').map((line, index) => (
                    <p key={`${index}-${line}`}>{line}</p>
                  ))}
                </div>
              ) : (
                <p className="text-xs leading-relaxed text-brand-700/90">
                  Descargá e instalá la actualización para obtener las últimas mejoras del sistema.
                </p>
              )}
              <Button size="sm" className="rounded-xl" onClick={() => void descargarActualizacion()}>
                <Download className="h-4 w-4" />
                Descargar actualización
              </Button>
            </div>
          )}

          {phase === 'downloading' && (
            <div className="space-y-2.5 rounded-xl border border-surface-border bg-slate-50/80 p-4">
              <div className="flex justify-between text-sm text-slate-600">
                <span className="flex items-center gap-2">
                  <Loader2 className="h-4 w-4 animate-spin text-brand-600" />
                  Descargando…
                </span>
                <span className="tabular-nums">
                  {downloadPercent}%{downloadDetail && ` · ${downloadDetail}`}
                </span>
              </div>
              <div className="h-2.5 overflow-hidden rounded-full bg-slate-200">
                <div
                  className="h-full rounded-full bg-brand-600 transition-all duration-300"
                  style={{ width: `${downloadPercent}%` }}
                />
              </div>
            </div>
          )}

          {phase === 'downloaded' && (
            <div className="space-y-3 rounded-xl border border-emerald-200 bg-gradient-to-br from-emerald-50/90 to-white p-4 ring-1 ring-emerald-100">
              <p className="text-sm font-semibold text-emerald-900">
                Versión {availableVersion} descargada. Reinicie para aplicar los cambios.
              </p>
              <Button size="sm" className="rounded-xl" onClick={() => void instalarActualizacion()}>
                Instalar y reiniciar
              </Button>
            </div>
          )}

          {phase === 'error' && errorMessage && (
            <div className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800 ring-1 ring-red-100">
              {errorMessage}
            </div>
          )}

          <div className="flex flex-wrap gap-2 pt-1">
            <Button
              variant="secondary"
              size="sm"
              className="rounded-xl"
              disabled={phase === 'checking' || phase === 'downloading'}
              onClick={() => void buscarActualizaciones()}
            >
              <RefreshCw className={cn('h-4 w-4', phase === 'checking' && 'animate-spin')} />
              Buscar actualizaciones
            </Button>
          </div>

          {isPackaged && (
            <p className="text-xs leading-relaxed text-slate-400">
              Las actualizaciones se descargan desde{' '}
              <a
                href="https://github.com/JRNCarrizo/bodegaStock/releases"
                className="text-brand-600 hover:underline"
                onClick={(e) => {
                  e.preventDefault()
                  window.open('https://github.com/JRNCarrizo/bodegaStock/releases', '_blank')
                }}
              >
                GitHub Releases
              </a>
              . Si esta versión fue instalada antes de v0.2.2, puede ser necesario actualizar
              manualmente una vez.
            </p>
          )}
        </CardBody>
      </Card>
    </div>
  )
}
